export const UNION_UNIFICATION_ENABLED = process.env.OPTIMIZE_UNIONS !== "0";
export const READ_LOWER_TARGET_INTERFACE_ENABLED = process.env.OPTIMIZE_TARGET_INTERFACE !== "0";

console.log(">>> UNION_UNIFICATION_ENABLED: ", UNION_UNIFICATION_ENABLED);
console.log(">>> READ_LOWER_TARGET_INTERFACE_ENABLED: ", READ_LOWER_TARGET_INTERFACE_ENABLED);
