export const LOCAL_STATE_TYPE_DEFS = "neo4j.graphql.typeDefs";
export const LOCAL_STATE_TYPE_LAST_QUERY = "neo4j.graphql.lastQuery";
export const LOCAL_STATE_LOGIN = "neo4j.graphql.login";

export const LOGIN_USERNAME_INPUT = "LOGIN_USERNAME_INPUT";
export const LOGIN_PASSWORD_INPUT = "LOGIN_PASSWORD_INPUT";
export const LOGIN_URL_INPUT = "LOGIN_URL_INPUT";
export const LOGIN_BUTTON = "LOGIN_BUTTON";

export const SCHEMA_EDITOR_INPUT = "SCHEMA_EDITOR_INPUT";
export const SCHEMA_EDITOR_BUILD_BUTTON = "SCHEMA_EDITOR_BUILD_BUTTON";

export const EDITOR_QUERY_INPUT = "EDITOR_QUERY_INPUT";
export const EDITOR_PARAMS_INPUT = "EDITOR_PARAMS_INPUT";
export const EDITOR_RESPONSE_OUTPUT = "EDITOR_RESPONSE_OUTPUT";
export const EDITOR_QUERY_BUTTON = "EDITOR_QUERY_BUTTON";
