[[auth-directive]]
= `@auth` directive

The `@auth` directive definition is dynamically generated at runtime based on user type definitions.

== `rules`

You can have many rules for many operations. Each rule is fallen through until a match is found against the corresponding operation. If no match is found, an error is thrown. You can think of rules as a big `OR`.

[source, graphql, indent=0]
----
@auth(rules: [
    { operations: [CREATE, UPDATE], ... }, ## or
    { operations: [READ, UPDATE], ...}, ## or
    { operations: [DELETE, UPDATE], ... } ## or
])
----

An auth rule can contain one of the four different kinds of check explained on the xref::auth/authorization/index.adoc[Authorization] documentation.

Different checks within a single rule can be combined together and all must succeed, or evaluate to true for an action to be allowed.  You can think of types of check within a rule as being combined with an `AND`.

[source, graphql, indent=0]
----
@auth(rules: [
    { 
        operations: [READ],
        roles: ["user"], ## and
        allow: { id: $jwt.sub }
    }, ## or
    { 
        operations: [READ],
        roles: ["admin"],
    }
])
----

In this example, for a caller to be allowed to see the data, they must have a JWT role of "user", or "admin", and if they have a role of "user", they are only permitted to read nodes with an id field matching their JWT subject.

You can also combine checks within a single rule using `OR`, or `AND` explicity and passing a list of sub-rules for example,

[source, graphql, indent=0]
----
@auth(rules: [
    { 
        operations: [READ],
        OR: [
            {
                roles: ["user"], ## and
                allow: { id: $jwt.sub }
            }, ## or
            {
                roles: ["admin"],
            }
        ]
    }
])
----

This rule has the same behavior as when the rules are specified separately.

== `operations`

`operations` is an array which allows you to re-use the same rule for many operations.

[source, graphql, indent=0]
----
@auth(rules: [
    { operations: [CREATE, UPDATE, DELETE, CONNECT, DISCONNECT] },
    { operations: [READ] }
])
----

NOTE: Note that the absence of an `operations` argument will imply _all_ operations.

Many different operations can be called at once, for example in the following Mutation:

[source, graphql, indent=0]
----
mutation {
    createPosts(
        input: [
            {
                content: "I like GraphQL",
                creator: { connect: { where: { id: "user-01" } } }
            }
        ]
    ) {
        posts {
            content
        }
    }
}
----

In the above example, there is a `CREATE` operation followed by a `CONNECT`, so the auth rule must allow a user to perform both of these operations.

The full list of operations and how they related to Cypher clauses are:

|===
|Operation |Cypher clause(s)

|`READ`
|`MATCH`

|`CREATE`
|`CREATE`

|`UPDATE`
|`SET`

|`DELETE`
|`DELETE`

|`CONNECT`
|`MATCH` and `MERGE`

|`DISCONNECT`
|`MATCH` and `DELETE`
|===

== Auth Value Plucking

When using the `@auth` directive, you use the following prefixes to substitute in their relevant values:

- `$jwt.` - pulls value from JWT
- `$context.` - pulls value from context
