[[subscriptions]]
= Subscriptions

xref::subscriptions/index.adoc[Subscriptions] can be used along with `@auth`, however, some operations are not supported. To setup rules,
use the `SUBSCRIBE` operation.

```graphql
type Movie {
    title: String!
}

extend type Movie @auth(rules: [{ isAuthenticated: true, operations: [SUBSCRIBE] }])
```

== Authentication
If the authentication rules `isAuthenticated` and `allowUnauthenticated` are not met, the subscription request will fail and no events will
be sent.

== Roles
Roles can be set for subscriptions. Only requests matching the roles set will be accepted.

== Bind
NOTE: Not Supported

== Where
If the rule `where` is set the provided arguments will be used on xref::subscriptions/filtering.adoc[subscriptions filtering], regardless
of the arguments provided by the client. Filtering using the `@auth` directive has the same limitations and behaviour as subscriptions filtering.

NOTE: If the same property is used for filtering in auth and in a query, auth filtering will take precedence.

== Allow
NOTE: Not Supported
