[[migration-guide]]
= Migration from `neo4j-graphql-js`

`@neo4j/graphql` was never intended to be a drop-in replacement for `neo4j-graphql-js`. However, simple applications should have a fairly trivial migration process.

== How to Upgrade

You need to uninstall the old library and install the new one (and its peer dependencies) using npm or your package manager of choice:

[source, bash, indent=0]
----
npm uninstall neo4j-graphql-js
npm install @neo4j/graphql graphql neo4j-driver
----

Subscriptions are not supported at this stage.

[[migration-guide-server]]
== Server

[[migration-guide-server-schema-generation]]
=== Schema Generation

In your server codebase, the process of creating an executable schema has changed. For a simple application, what used to be:

[source, javascript, indent=0]
----
const { makeAugmentedSchema } = require("neo4j-graphql-js");

const typeDefs = require("./type-definitions");

const schema = makeAugmentedSchema({ typeDefs });
----

Has become:

[source, javascript, indent=0]
----
const { Neo4jGraphQL } = require("@neo4j/graphql");

const typeDefs = require("./type-definitions");

const neo4jGraphQL = new Neo4jGraphQL({ typeDefs });

const schema = await neo4jGraphQL.getSchema();
----

Additionally, the `Neo4jGraphQL` constructor allows you to pass in a driver instance instead of passing one in the context of each request.

=== Schema Configuration

The `neo4j-graphql-js` library would allow a user to configure the GraphQL schema via the `makeAugmentedSchema()` function.

For example, to exclude all queries and all mutations:

[source, javascript, indent=0]
----
const schema = makeAugmentedSchema({
  typeDefs,
  config: {
    query: false, // exclude all queries
    mutation: false // exclude all mutations
  }
});
----

Or to exclude queries for a specific type like so:

[source, javascript, indent=0]
----
const schema = makeAugmentedSchema({
  typeDefs,
  config: {
    query: {
      exclude: ["NameOfTypeToExclude"] // exclude query for type NameOfTypeToExclude
    },
    mutation: false // exclude all mutations
  }
});
----

To achieve the same behaviour with the new `@neo4j/graphql` library, the GraphQL schema has to be extended instead. Note, no additional configuration or parameters need to be passed to the `getSchema()` function.

To exclude all mutations for a specific type:
[source, graphql, indent=0]
----
type NameOfType @exclude(operations: [CREATE, UPDATE, DELETE]) {
  name: String
}
----

Or to exclude all queries and all mutations for a specific type like so:

[source, graphql, indent=0]
----
type NameOfTypeToExclude @exclude {
  name: String
}
----
For more information regarding the above used `@exclude` directive, see xref::reference/directives/access-control.adoc#type-definitions-access-control-exclude[`@exclude`].


=== Database Configuration

==== Driver

Once a schema has been generated, it can be passed into a GraphQL server instance with the driver in the context, identical to using the old library. For example, using Apollo Server and using the schema generated above:

[source, javascript, indent=0]
----
const { ApolloServer } = require("apollo-server");

const driver = require("./driver");
const schema = require("./schema");

const server = new ApolloServer({ schema, context: { driver } });

server.listen().then(({ url }) => {
    console.log(`@neo4j/graphql API ready at ${url}`);
});
----

==== Multiple Databases

Multiple databases were supported in `neo4j-graphql-js` by passing a context key `neo4jDatabase` with the name of a database, for example for database called "sanmateo":

[source, javascript, indent=0]
----
const { ApolloServer } = require("apollo-server");

const driver = require("./driver");
const schema = require("./schema");

const server = new ApolloServer({ schema, context: { driver, neo4jDatabase: "sanmateo" } });

server.listen().then(({ url }) => {
    console.log(`@neo4j/graphql API ready at ${url}`);
});
----

In `@neo4j/graphql`, this has now become:

[source, javascript, indent=0]
----
const { ApolloServer } = require("apollo-server");

const driver = require("./driver");
const schema = require("./schema");

const server = new ApolloServer({ schema, context: { driver, driverConfig: { database: "sanmateo" } } });

server.listen().then(({ url }) => {
    console.log(`@neo4j/graphql API ready at ${url}`);
});
----

Database bookmarks are also supported. See xref::reference/driver-configuration.adoc[Driver Configuration] for more information.

[[migration-guide-type-definitions]]
== Type Definitions

This page will walk through what needs to change in your type definitions before you can pass them into `@neo4j/graphql`.

=== Directives

Both `neo4j-graphql-js` and `@neo4j/graphql` are highly driven by GraphQL directives. Each heading in this section will address how/if one or many directives available in `neo4j-graphql-js` can be migrated to `@neo4j/graphql`.

==== `@relation`

Migrating this directive is trivial:

1. Rename `@relation` to `@relationship`
2. Rename the argument `name` to `type`

For example, `@relation(name: "ACTED_IN", direction: OUT)` becomes `@relationship(type: "ACTED_IN", direction: OUT)`.

See xref::reference/type-definitions/relationships.adoc[Relationships] for more information on relationships in `@neo4j/graphql`.

==== Relationship Properties

If for instance using `neo4j-graphql-js`, you have the following type definitions defining an `ACTED_IN` relationship with a `roles` property:

[source, graphql, indent=0]
----
type Actor {
    movies: [ActedIn!]!
}

type Movie {
    actors: [ActedIn!]!
}

type ActedIn @relation(name: "ACTED_IN") {
    from: Actor
    to: Movie
    roles: [String!]
}
----

This will need to be refactored to the following in the new library:

[source, graphql, indent=0]
----
type Actor {
    movies: [Movie!]! @relationship(type: "ACTED_IN", properties: "ActedIn", direction: OUT)
}

type Movie {
    actors: [Actor!]! @relationship(type: "ACTED_IN", properties: "ActedIn", direction: IN)
}

interface ActedIn @relationshipProperties {
    roles: [String!]
}
----

Note the following changes to the `ActedIn` type:

* Changed from `type` to `interface`
* Removed `@relation` directive
* Removed `from` and `to` fields

And note the following changes to the two node types:

* Relationship field types changed from the relationship type to the neighbouring node type
* Normal `@relationship` directive added to each relationship field, with an additional `properties` argument pointing to the relationship properties interface

=== `@cypher`

No change. See xref::reference/directives/cypher.adoc[`@cypher` directive] for more details on this directive in `@neo4j/graphql`.

==== `@neo4j_ignore`

`@neo4j/graphql` offers two directives for skipping autogeneration for specified types/fields:

* xref::reference/directives/access-control.adoc#type-definitions-access-control-exclude[`@exclude`]: Skip generation of specified Query/Mutation fields for an object type
* xref::custom-resolvers.adoc#custom-resolver-directive[`@customResolver`]: Ignore a field, which will need custom logic for resolution

==== `@isAuthenticated`, `@hasRole` and `@hasScope`

Will require significant migration, but will be worth the effort! See xref::auth/index.adoc[Authentication and Authorization].

==== `@additionalLabels`

Not supported at this time.

==== `@id`

There is an equivalent directive in the new library, but it does not work using database constraints as per the old library. See xref::reference/directives/autogeneration.adoc#type-definitions-autogeneration-id[`@id`].

==== `@unique`, `@index` and `@search`

These all relate to database indexes and constraints, which are not currently supported by `@neo4j/graphql`.

=== Types

==== Scalar Types

Supported as you would expect, with additional xref::reference/type-definitions/types.adoc#type-definitions-types-bigint[`BigInt`] support for 64 bit integers.

==== Temporal Types (`DateTime`, `Date`)

Temporal Types have been massively simplified in `@neo4j/graphql`, down to `DateTime` and `Date`, which use ISO 8601 and "yyyy-mm-dd" strings respectively for parsing and serialization.

In terms of migrating from the old library, the `formatted` field of the old `DateTime` type now becomes the value itself. For example, used in a query:

[source, graphql, indent=0]
----
{
  Movie(released: { formatted: "1992-10-09T00:00:00Z" }) {
    title
  }
}
----

Has become:

[source, graphql, indent=0]
----
{
  Movie(released: "1992-10-09T00:00:00Z") {
    title
  }
}
----

Due to the move to ISO 8601 strings, input types are no longer necessary for temporal instances, so `_Neo4jDateTimeInput` has become `DateTime` and `_Neo4jDateInput` has become `Date` for input.

See xref::reference/type-definitions/types.adoc#type-definitions-types-temporal[Temporal Types].

==== Spatial Types

The single type in `neo4j-graphql-js`, `Point`, has been split out into two types:

* xref::reference/type-definitions/types.adoc#type-definitions-types-point[`Point`]
* xref::reference/type-definitions/types.adoc#type-definitions-types-cartesian-point[`CartesianPoint`]

Correspondingly, `_Neo4jPointInput` has also been split out into two input types:

* `PointInput`
* `CartesianPointInput`

Using them in Queries and Mutations should feel remarkably similar.

==== Interface Types

Supported, queryable using inline fragments as per `neo4j-graphql-js`, but can also be created using Nested Mutations. See xref::reference/type-definitions/interfaces.adoc[Interfaces].

==== Union Types

Supported, queryable using inline fragments as per `neo4j-graphql-js`, but can also be created using Nested Mutations. See xref::reference/type-definitions/unions.adoc#type-definitions-unions[Unions].

=== Fields

==== `_id`

An `_id` field exposing the underlying node ID is not included in each type by default in `@neo4j/graphql` like it was in `neo4j-graphql-js`. If you require this functionality (however, it should be noted that underlying node IDs should not be relied on because they can be reused), you can include a field definition such as in the following type definition:

[source, graphql, indent=0]
----
type ExampleType {
  _id: ID! @cypher(statement: "RETURN ID(this)")
}
----

[[migration-guide-queries]]
== Queries

Using `neo4j-graphql-js`, all of the arguments for a Query were root-level arguments. For example, for the following simple type definition:

[source, graphql, indent=0]
----
type Movie {
    title: String!
    averageRating: Float
}
----

The following Query would have been generated:

[source, graphql, indent=0]
----
type Query {
    Movie(title: String, averageRating: Float, first: Int, offset: Int, orderBy: [_MovieOrdering], filter: _MovieFilter): [Movie]
}
----

In `@neo4j/graphql`, the ethos has been to simplify the top-level arguments:

[source, graphql, indent=0]
----
type Query {
    movies(where: MovieWhere, options: MovieOptions): [Movie]!
}
----

Changes to note for migration:

* Query fields were previously named in the singular, and in _PascalCase_ - they are now pluralized and in _camelCase_
* Query return types were previously in nullable lists of nullable types - they are now non-nullable lists of non-nullable types, _e.g._ `[Movie]` is now `[Movie!]!`; ensuring either an array of defined `Movie` objects or an empty array.
* In this example, the `_MovieFilter` type has essentially been renamed to `MovieWhere`, the `filter` arguments renamed to `where`, and the top-level field arguments `title` and `averageRating` removed - see xref::migration/index.adoc#migration-guide-queries-filtering[Filtering (`where`)] below
* The `first`, `offset` and `orderBy` have been collapsed into the `MovieOptions` type and renamed `limit`, `offset` and `sort`, respectively - see xref::migration/index.adoc#migration-guide-queries-options[Sorting and Pagination (`options`)] below.

[[migration-guide-queries-filtering]]
=== Filtering (`where`)

Simple equality fields are no longer available at the root of Query fields. As a simple demonstration, a simple query using `neo4j-graphql-js` that looked like:

[source, graphql, indent=0]
----
query {
    Movie(title: "Forrest Gump") {
        averageRating
    }
}
----

Is now changed to the following using `@neo4j/graphql`:

[source, graphql, indent=0]
----
query {
    movies(where: { title: "Forrest Gump" }) {
        averageRating
    }
}
----

When discussing how the field `where` of type `MovieWhere` differs to the field `filter` of `_MovieFilter` the following table can be used for guidance:

.Comparing the fields of the `_MovieFilter` and `MovieWhere` types
[cols="1,1"]
|===
|`neo4j-graphql-js` |`@neo4j/graphql`

|`AND: [_MovieFilter!]`
|`AND: [MovieWhere!]`

|`OR: [_MovieFilter!]`
|`OR: [MovieWhere!]`

|`NOT: _MovieFilter!`
|`NOT: MovieWhere!`

|`title: String`
|`title: String`

|`title_in: [String!]`
|`title_IN: [String!]`

|`title_contains: String`
|`title_CONTAINS: String`

|`title_starts_with: String`
|`title_STARTS_WITH: String`

|`title_ends_with: String`
|`title_ENDS_WITH: String`

|`title_regexp: String`
|`title_MATCHES: String`

|`averageRating: Float`
|`averageRating: Float`

|`averageRating_in: [Float!]`
|`averageRating_IN: [Float]`

|`averageRating_lt: Float`
|`averageRating_LT: Float`

|`averageRating_lte: Float`
|`averageRating_LTE: Float`

|`averageRating_gt: Float`
|`averageRating_GT: Float`

|`averageRating_gte: Float`
|`averageRating_GTE: Float`
|===

For filtering on relationship fields, the `_some`, `_none`, `_single` and `_every` filters are not yet implemented.

[[migration-guide-queries-options]]
=== Sorting and Pagination (`options`)

==== Sorting

Sorting has changed somewhat in `@neo4j/graphql`. For the example being used in this page, the `_MovieOrdering` type in `neo4j-graphql-js` was an enum which looked like the following:

[source, graphql, indent=0]
----
enum _MovieOrdering {
    title_asc
    title_desc
    averageRating_asc
    averageRating_desc
}
----

You could then query all movies ordered by title ascending by executing:

[source, graphql, indent=0]
----
query {
    Movie(orderBy: [title_asc]) {
        title
    }
}
----

In `@neo4j/graphql`, the sorting type `MovieSort` has become an input type with each field as an enum, like follows:

[source, graphql, indent=0]
----
enum SortDirection {
    ASC
    DESC
}

input MovieSort {
    title: SortDirection
    averageRating: SortDirection
}
----

To fetch all movies sorted by title ascending as per above, you would execute:

[source, graphql, indent=0]
----
query {
    movies(options: { sort: [{ title: ASC }] }) {
        title
    }
}
----

==== Pagination

Pagination is broadly similar, with the arguments just renamed and moved a level deeper. For example, to return "page 3, with 10 results per page" using `neo4j-graphql-js` was:

[source, graphql, indent=0]
----
query {
    Movie(offset: 20, first: 10) {
        title
    }
}
----

Using `@neo4j/graphql`, this will now be:

[source, graphql, indent=0]
----
query {
    movies(options: { offset: 20, limit: 10 }) {
        title
    }
}
----

[[migration-guide-mutations]]
== Mutations

This section will walk through each operation available through GraphQL Mutations, and how to migrate each from `neo4j-graphql-js` to `@neo4j/graphql`.

The examples in this section will be based off the following type definitions (which have been migrated over to `@neo4j/graphql` syntax):

[source, graphql, indent=0]
----
type Actor {
    name: String!
    movies: [Movie!]! @relationship(type: "ACTED_IN", direction: OUT)
}

type Movie {
    title: String!
    averageRating: Float
    actors: [Actor!]! @relationship(type: "ACTED_IN", direction: IN)
}
----

A summary of migration points is as follows:

* Mutations which were previously in the singular and in _PascalCase_ are now pluralized and in _camelCase_ - for example `CreateMovie` has become `createMovies`
* Connect and disconnect Mutations are no longer present, these operations are accessed through an update Mutation
* The object(s) being mutated are returned as a nested field, to allow for metadata about the operation to be added in future
* Mutation arguments are now commonly named between different types, but with different input types - such as `where` and `input`

> Note that xref::mutations/index.adoc[Mutations] in `@neo4j/graphql` are incredibly powerful, and it is well worthwhile reading about them in full. You might find that you can collapse multiple current mutations down into one!

=== Creating

For creating nodes, the input arguments of `neo4j-graphql` have been moved inside an `input` argument in `@neo4j/graphql`.

For example, creating a movie using the old library:

[source, graphql, indent=0]
----
mutation {
    CreateMovie(title: "Forrest Gump") {
        title
    }
}
----

Looks like the following using `@neo4j/graphql`:

[source, graphql, indent=0]
----
mutation {
    createMovies(input: { title: "Forrest Gump" }) {
        movies {
            title
        }
    }
}
----

Note that `movies` must also be first selected in the selection set.

=== Updating

An update Mutation using `neo4j-graphql-js` had all of the arguments at the root of the Mutation, including the filter and fields to change.

This has all changed in `@neo4j/graphql`, with a `where` argument to select the node, and then an `update` argument (amongst many others) to select what to update.

For example, updating the average rating of the Movie Forrest Gump:

[source, graphql, indent=0]
----
mutation {
    UpdateMovie(title: "Forrest Gump", averageRating: 5.0) {
        title
        averageRating
    }
}
----

Will look like the following using the new library:

[source, graphql, indent=0]
----
mutation {
    updateMovies(where: { title: "Forrest Gump" }, update: { averageRating: 5.0 }) {
        movies {
            title
            averageRating
        }
    }
}
----

=== Deleting

The arguments for selecting which node to delete have now been moved into a `where` argument.

Additionally, the return value is now a `DeleteInfo` object informing how many nodes and relationships were deleted.

For example, deleting a movie:

[source, graphql, indent=0]
----
mutation {
    DeleteMovie(title: "Forrest Gump") {
        title
    }
}
----

Looks like the following using `@neo4j/graphql`:

[source, graphql, indent=0]
----
mutation {
    deleteMovies(where: { title: "Forrest Gump" }) {
        nodesDeleted
        relationshipsDeleted
    }
}
----

=== Connecting

Using `neo4j-graphql-js`, connecting two of the nodes in this example would have been achieved by executing either the `AddMovieActors` or `AddActorMovies` Mutation.

In `@neo4j/graphql`, this is achieved by specifying the `connect` argument on either the `updateMovies` or `updateActors` Mutation.

For example:

[source, graphql, indent=0]
----
mutation {
    AddMovieActors(from: { name: "Tom Hanks" }, to: { title: "Forrest Gump" }) {
        from {
            name
        }
        to {
            title
        }
    }
}
----

Would become the following using `@neo4j/graphql`:

[source, graphql, indent=0]
----
mutation {
    updateMovies(
        where: { title: "Forrest Gump" }
        connect: { actors: { where: { node: { name: "Tom Hanks" } } } }
    ) {
        movies {
            title
            actors {
                name
            }
        }
    }
}
----

Note, there are many ways to achieve the same goal using the powerful Mutation ability of `@neo4j/graphql`, so do what feels best for your data!

=== Disconnecting

Similarly to connecting, using `neo4j-graphql-js`, disconnecting two of the nodes in this example would have been achieved by executing either the `RemoveMovieActors` or `RemoveActorMovies` Mutation.

In `@neo4j/graphql`, this is achieved by specifying the `disconnect` argument on either the `updateMovies` or `updateActors` Mutation.

For example:

[source, graphql, indent=0]
----
mutation {
    RemoveMovieActors(from: { name: "Tom Hanks" }, to: { title: "Forrest Gump" }) {
        from {
            name
        }
        to {
            title
        }
    }
}
----

Would become the following using `@neo4j/graphql`:

[source, graphql, indent=0]
----
mutation {
    updateMovies(
        where: { title: "Forrest Gump" }
        disconnect: { actors: { where: { node: { name: "Tom Hanks" } } } }
    ) {
        movies {
            title
            actors {
                name
            }
        }
    }
}
----

In the result field `actors`, Tom Hanks should no longer be present.

