/*
 * Copyright (c) "Neo4j"
 * Neo4j Sweden AB [http://neo4j.com]
 */

import type { UniqueType } from "../../utils/graphql-types";
import { TestHelper } from "../../utils/tests-helper";

describe("https://github.com/neo4j/graphql/issues/1817", () => {
    const testHelper = new TestHelper();

    let TypeContainerType: UniqueType;
    let TypeContainer: UniqueType;
    let TypeMaterial: UniqueType;

    beforeAll(async () => {
        TypeContainerType = testHelper.createUniqueType("ContainerType");
        TypeContainer = testHelper.createUniqueType("Container");
        TypeMaterial = testHelper.createUniqueType("Material");

        const typeDefs = `
            type ${TypeContainerType} @node {
                id: ID! @id
                name: String!
                specifiesContainers: [${TypeContainer}!]!
                    @relationship(type: "hasContainer", properties: "CoT_Co_hasContainer", direction: OUT)
            }
    
            type ${TypeContainer} @node {
                id: ID! @id
                name: String
                containsMaterial: [${TypeMaterial}!]!
                    @relationship(type: "hasMaterial", properties: "Co_Ma_hasMaterial", direction: OUT)
            }
    
            type ${TypeMaterial} @node {
                id: ID! @id
                name: String
            }
    
            type CoT_Co_hasContainer @relationshipProperties {
                id: ID! @id 
            }
    
            type Co_Ma_hasMaterial @relationshipProperties {
                id: ID! @id 
            }
        `;
        await testHelper.initNeo4jGraphQL({
            typeDefs,
        });
    });

    afterAll(async () => {
        await testHelper.close();
    });

    test("Using alias for an autogenerated connection should not fail", async () => {
        const query = `
            {
                ${TypeContainerType.plural}{
                  specifiesContainers {
                    AliasNestedLevel2: containsMaterialConnection {
                      edges {
                        node {
                          id
                        }
                      }
                    }
                  }
                }
              }
            `;

        const res = await testHelper.executeGraphQL(query);

        expect(res.errors).toBeUndefined();

        expect(res.data).toEqual({
            [TypeContainerType.plural]: [],
        });
    });
});
