/*
 * Copyright (c) "Neo4j"
 * Neo4j Sweden AB [http://neo4j.com]
 */

import type { ConcreteEntityAdapter } from "../../../../schema-model/entity/model-adapters/ConcreteEntityAdapter";
import type { RelationshipAdapter } from "../../../../schema-model/relationship/model-adapters/RelationshipAdapter";
import { IdField } from "../../ast/input-fields/IdField";
import { TimestampField } from "../../ast/input-fields/TimestampField";
import { isConcreteEntity } from "../../utils/is-concrete-entity";

export function getAutogeneratedFields(
    target: ConcreteEntityAdapter | RelationshipAdapter
): (IdField | TimestampField)[] {
    const attachedTo = isConcreteEntity(target) ? "node" : "relationship";
    const autoGeneratedFields: (IdField | TimestampField)[] = [];
    for (const attribute of target.attributes.values()) {
        if (attribute.timestampCreateIsGenerated()) {
            autoGeneratedFields.push(new TimestampField(attribute.name, attribute, attachedTo));
        }
        if (attribute.annotations.id) {
            autoGeneratedFields.push(new IdField(attribute.name, attribute, attachedTo));
        }
    }
    return autoGeneratedFields;
}

export function getAutogeneratedFieldsForUpdate(
    target: ConcreteEntityAdapter | RelationshipAdapter
): (IdField | TimestampField)[] {
    const attachedTo = isConcreteEntity(target) ? "node" : "relationship";
    const autoGeneratedFields: (IdField | TimestampField)[] = [];
    for (const attribute of target.attributes.values()) {
        if (attribute.timestampUpdateIsGenerated()) {
            autoGeneratedFields.push(new TimestampField(attribute.name, attribute, attachedTo));
        }
    }
    return autoGeneratedFields;
}
