[[directives]]
= Directives

== `@auth`

The `@auth` directive is used to define complex fine-grained and role-based access control for object types and fields.

Reference: <<auth-directive>>

== `@coalesce`

The `@coalesce` directive exposes a mechanism for querying against non-existent, `null` values on a node.

Reference: <<type-definitions-default-values-coalesce>>

== `@cypher`

The `@cypher` directive overrides field resolution (including `Query` and `Mutation` fields), instead resolving with the specified Cypher.

Reference: <<type-definitions-cypher>>

== `@default`

The `@default` directive allows for the setting of a default value for a field on object creation.

Reference: <<type-definitions-default-values-default>>

== `@exclude`

The `@exclude` directive is used on object types to instruct them to be skipped during Query and Mutation generation.

Reference: <<type-definitions-access-control-exclude>>

== `@id`

The `@id` directive marks a field as the unique ID for an object type, and allows for autogeneration of IDs.

Reference: <<type-definitions-autogeneration-id>>

== `@ignore`

The `@ignore` directive ignores a field, and it will need an alternative mechanism for resolution.

Reference: <<type-definitions-access-control-ignore>>

== `@private`

The `@private` directive protects fields which should only be available through the <<ogm>>.

Reference: <<ogm-private>>

== `@readonly`

The `@readonly` directive marks fields as read-only.

Reference: <<type-definitions-access-control-readonly>>

== `@relationship`

The `@relationship` directive is used to configure relationships between object types.

Reference: <<type-definitions-relationships>>

== `@timestamp`

The `@timestamp` directive flags fields to be used to store timestamps on create/update events.

Reference: <<type-definitions-autogeneration-timestamp>>

== `@writeonly`

The `@writeonly` directive marks fields as write-only.

Reference: <<type-definitions-access-control-writeonly>>
