[[directives]]
= Directives

== `@cypher`

Reference: <<type-definitions-cypher>>

== `@relationship`

Reference: <<type-definitions-relationships>>

== `@exclude`
This directive can be used to tell `Neo4jGraphQL` to skip the automatic generation of the Query or Mutations for a certain type.

Reference: <<type-definitions-access-control-exclude>>

== `@auth`

See <<auth>>

== `@autogenerate`

Reference: <<type-definitions-autogeneration-autogenerate>>

== `@private`
The `@private` directive allows you to specify fields that should only be accessible through the <<ogm>>. This is very handy as you can hide fields such as user password to the outside world. Simply put the @private directive on the field you wish to be inaccessible through the exposed API.

Reference: <<type-definitions-access-control-private>>

== `@readonly`
The field will only feature in object types for querying, and will not be mutable.

Reference: <<type-definitions-access-control-readonly>>

== `@writeonly`
This field will only feature in input types, and will not be available for querying the object type through a Query or through a Mutation response.

Reference: <<type-definitions-access-control-writeonly>>

== `@ignore`
This field will essentially be completely ignored, and will require another way to resolve the field, such as through the use of a custom resolver.

Reference: <<type-definitions-access-control-ignore>>

== `@default`

When generating the input type for the create mutation, the value specified in this directive will be used as the default value for this field.

Reference: <<type-definitions-default-values-default>>

== `@coalesce`

When translating from GraphQL to Cypher, any instances of fields to which this directive is applied will be wrapped in a `coalesce()` function in the WHERE clause (see https://neo4j.com/developer/kb/understanding-non-existent-properties-and-null-values/#_use_coalesce_to_use_a_default_for_a_null_value). This helps to query against non-existent properties in a database, however it is encouraged to populate these properties with meaningful values if this is becoming the norm. This is a very primitive implementation of the function which only takes a static default value as opposed to using another property in a node or a Cypher expression.

Reference: <<type-definitions-default-values-coalesce>>
