[[ogm]]
= OGM

Common applications won't just expose a single API. On the same instance as the GraphQL API there may be; scheduled jobs, authentication, migrations and not to forget any custom logic in the resolvers themselves. We expose a OGM(Object Graph Model) on top of the pre-existing GraphQL work and abstractions. 


== Quick Start

Generate your normal GraphQL schema & use the exposed ``.model` method to receive an instance of a model. 

[source, javascript]
----
import { OGM } from "@neo4j/graphql";
import * as neo4j from "neo4j-driver";

const typeDefs = `
    type Movie {
        id: ID
        name: String
    }
`;

const driver = neo4j.driver("bolt://localhost:7687", neo4j.auth.basic("admin", "password"));

const ogm = new OGM({ typeDefs, driver });

const Movie = ogm.model("Movie");

const [theMatrix] = await Movie.find({ where: { name: "The Matrix" } });
----

== Methods

You can call the following on the model;

. find
. create
. delete
. update

Each method maps to the underlying generated Query or Mutation for that Model.

== `@private`
The `@private` directive allows you to specify fields that should only be accessible through the OGM. This is very handy as you can hide fields such as user password to the outside world. Simply put the `@private` directive on the field you wish to be inaccessible through the exposed API;

[source, graphql]
----
type User {
    username: String!
    email: String!
    password: String! @private
}
----

Using the password field is a great example here. In your application, you would want to hash passwords & hide them from snoopers. You could have a custom resolver, using the OGM, to update and set passwords. This is more apparent when you want to use the same type definitions to drive a public-facing schema and an OGM;

[source, javascript]
----
import { Neo4jGraphQL, OGM } from "@neo4j/graphql";
import * as neo4j from "neo4j-driver";

const driver = neo4j.driver(
    "bolt://localhost:7687",
    neo4j.auth.basic("admin", "password")
);

const typeDefs = `
    type User {
        username: String!
        email: String!
        password: String! @private
    }
`;

// public without password 
const neoSchema = new Neo4jGraphQL({ typeDefs, context: { driver } });

// private with access to password
const ogm = new OGM({ typeDefs, driver });

const apolloServer = new ApolloServer({ schema: neoSchema.schema });
----

We also exclude the following directives from OGM generation;

1. `@auth`
2. `@exclude`

== Selection Set 
This is a GraphQL specific term. When you preform a query you have the operation;

[source, graphql]
----
query {
    myOperation
}
----

And you also have a Selection Set;

[source, graphql]
----
query {
    myOperation {
        # Selection Set start
        id
        name
    } # Selection Set end
}
----

When using the OGM we do not want users providing a selections sets... Doing so would make the OGM feel more like querying the GraphQL Schema when the OGM is designed as an abstraction ontop of it. To combat this we do Autogenerated Selection Sets. Given a Node;

[source, graphql]
----
type Node {
    id: ID
    name: String
    relation: [Node] @relationship(...)
    customCypher: [Node] @cypher(...)
}
----

We pre-generate a pre-defined selection set. We don't include any relationships or cypher fields, as they could be computationally expensive. Given the above Node the auto pre-defined selection set would be;

[source, graphql]
----
{
    id
    name
}
----

This means that by default, querying for Node(s), you would only get the `.id` and `.name` properties returned. If you want to select more you can either define a selection set at execution time or as a static on the Model;

===  Selection set at execution time

[source, javascript]
----
import { OGM } from "@neo4j/graphql";
import * as neo4j from "neo4j-driver";

const driver = neo4j.driver(
    "bolt://localhost:7687",
    neo4j.auth.basic("admin", "password")
);

const typeDefs = `
    type Node {
        id: ID
        name: String
        relation: [Node] @relationship(...)
        customCypher: [Node] @cypher(...)
    }
`;

const ogm = new OGM({ typeDefs, driver });
const Node = ogm.model("Node");

const selectionSet = `
    {
        id
        name
        relation {
            id
            name
        }
        customCypher {
            id
            name
        }
    }
`;
const nodes = await Node.find({ selectionSet });
----

===  Selection set as a static

[source, javascript]
----
import { OGM } from "@neo4j/graphql";
import * as neo4j from "neo4j-driver";

const driver = neo4j.driver(
    "bolt://localhost:7687",
    neo4j.auth.basic("admin", "password")
);

const typeDefs = `
    type Node {
        id: ID
        name: String
        relation: [Node] @relationship(...)
        customCypher: [Node] @cypher(...)
    }
`;

const ogm = new OGM({ typeDefs, driver });
const Node = ogm.model("Node");

const selectionSet = `
    {
        id
        name
        relation {
            id
            name
        }
        customCypher {
            id
            name
        }
    }
`;
Node.setSelectionSet(selectionSet)
----
