[[schema-configuration-field-configuration]]
= Field Configuration

In case you need to remove fields from a GraphQL Object Type or a GraphQL Input Object Type, consider the following type definitions:

[source, graphql, indent=0]
----
type Movie {
    title: String!
    description: String
}

type Actor {
    name: String!
    age: Int
    actedIn: [Movie!]! @relationship(type: "ACTED_IN", direction: OUT)
}
----

It will generate the type `Actor`:

[source, graphql, indent=0]
----
type Actor {
  name: String!
  age: Int
  actedIn(where: MovieWhere, options: MovieOptions, directed: Boolean = true): [Movie!]!
  actedInAggregate(where: MovieWhere, directed: Boolean = true): ActorMovieActedInAggregationSelection
  actedInConnection(where: ActorActedInConnectionWhere, first: Int, after: String, directed: Boolean = true, sort: [ActorActedInConnectionSort!]): ActorActedInConnection!
}
----

By using the directives `@selectable`, `@settable`, and `@relationship` it is possible to control how these fields are exposed.
For instance, to hide the field `age` in the Selection Set, you can use the `@selectable` directive:

[source, graphql, indent=0]
----
type Movie {
    title: String!
    description: String
}

type Actor {
    name: String!
    age: Int @selectable(onRead: false, onAggregate: false)
    actedIn: [Movie!]! @relationship(type: "ACTED_IN", direction: OUT)
}
----

Now the type `Actor` will look like this:

[source, graphql, indent=0]
----
type Actor {
  name: String!
  actedIn(where: MovieWhere, options: MovieOptions, directed: Boolean = true): [Movie!]!
  actedInAggregate(where: MovieWhere, directed: Boolean = true): ActorMovieActedInAggregationSelection
  actedInConnection(where: ActorActedInConnectionWhere, first: Int, after: String, directed: Boolean = true, sort: [ActorActedInConnectionSort!]): ActorActedInConnection!
}
----

== `@relationship`

There are several nested operations available for every field created using the `@relationship` directive. These are `create`, `connect`, `disconnect`, `connectOrCreate`, `delete`. 

However, these operations are not always needed. 
The `@relationship` directive allows you to define which operations should be available for a relationship by using the argument `nestedOperations`.

Additionally, the `@relationship` directive causes fields to be added for nested aggregations. These can be disabled using the `aggregate` argument.

=== Definition

[source, graphql, indent=0]
----
enum NestedOperations {
    CREATE
    UPDATE
    DELETE
    CONNECT
    DISCONNECT
    CONNECT_OR_CREATE
}

directive @relationship(
    type: String!
    queryDirection: RelationshipQueryDirection! = DEFAULT_DIRECTED
    direction: RelationshipDirection!
    properties: String
    nestedOperations: [NestedOperations!]! = [CREATE, UPDATE, DELETE, CONNECT, DISCONNECT, CONNECT_OR_CREATE]
    aggregate: Boolean! = true
) on FIELD_DEFINITION
----

[NOTE]
====
In version 4.0.0, `aggregate` is `false` as default.
See xref:migration/v4-migration.adoc#_relationship_changes[`@relationship changes`] for more information.
====

=== Usage

==== Configure aggregation

From the previous type definitions, the type `Actor` produced is:

[source, graphql, indent=0]
----
type Actor {
  name: String!
  actedIn(where: MovieWhere, options: MovieOptions, directed: Boolean = true): [Movie!]!
  actedInAggregate(where: MovieWhere, directed: Boolean = true): ActorMovieActedInAggregationSelection
  actedInConnection(where: ActorActedInConnectionWhere, first: Int, after: String, directed: Boolean = true, sort: [ActorActedInConnectionSort!]): ActorActedInConnection!
}
----

As it's visible, the relationship field `actedIn` produces the operation field `actedInAggregate` which allows aggregations on that relationship. It's possible to configure this behavior by passing the argument aggregate on the `@relationship` directive:

[source, graphql, indent=0]
----
type Movie {
    title: String!
    description: String
}

type Actor {
    name: String!
    age: Int
    actedIn: [Movie!]! @relationship(type: "ACTED_IN", direction: OUT, aggregate: false)
}
----

In this case, as we passed the argument `aggregate` as false, the type `Actor` produced is:

[source, graphql, indent=0]
----
type Actor {
  name: String!
  age: Int
  actedIn(where: MovieWhere, options: MovieOptions, directed: Boolean = true): [Movie!]!
  actedInConnection(where: ActorActedInConnectionWhere, first: Int, after: String, directed: Boolean = true, sort: [ActorActedInConnectionSort!]): ActorActedInConnection!
}
----

=== Configure nested operations

A large part of the schema produced by the library is needed to support nested operations. These are enabled by the directive `@relationship` as described in xref:reference/type-definitions/relationships.adoc#_inserting_data[@relationship Inserting Data].

The nested operations available are:

[source, graphql, indent=0]
----
enum NestedOperations {
    CREATE
    UPDATE
    DELETE
    CONNECT
    DISCONNECT
    CONNECT_OR_CREATE
}
----

By default, the `@relationship` enables all of them when defined. To enable only some of them, you have to pass the argument `nestedOperations` specifying the operations required.

**Disable nested create**

To disable the nested `CREATE` operation, change the initial type definitions to:

[source, graphql, indent=0]
----
type Movie {
    title: String!
    description: String
}

type Actor {
    name: String!
    age: Int
    actedIn: [Movie!]! @relationship(type: "ACTED_IN", direction: OUT, nestedOperations: [UPDATE, DELETE, CONNECT, DISCONNECT, CONNECT_OR_CREATE])
}
----

As the `CREATE` operation is not present in the `nestedOperations` argument array, it will be no longer possible to create movies starting from the `Actor` type.

**Disable all nested operations**

If instead, no nested operations are required, it's possible to disable all the nested operations by passing an empty array, as:

[source, graphql, indent=0]
----
type Movie {
    title: String!
    description: String
}

type Actor {
    name: String!
    age: Int
    actedIn: [Movie!]! @relationship(type: "ACTED_IN", direction: OUT, nestedOperations: [])
}
----

== `@selectable`

This directive sets the availability of fields on queries and aggregations. 
It has two arguments:

* **onRead**: If disabled, this field will not be available on queries and subscriptions.
* **onAggregate**: If disabled, aggregations will not be available for this field.

=== Definition

[source, graphql, indent=0]
----
"""Instructs @neo4j/graphql to generate this field for selectable fields."""
directive @selectable(onRead: Boolean! = true, onAggregate: Boolean! = true) on FIELD_DEFINITION
----

=== Usage

With the following definition:

[source, graphql, indent=0]
----
type Movie {
    title: String!
    description: String @selectable(onRead: false, onAggregate: true)
}
----

The type `Movie` in the resulting schema will look like this:

[source, graphql, indent=0]
----
type Movie {
    title: String!
}
----

This means that descriptions cannot be queried, either on top or on nested levels. 
Aggregations, however, are available on both:

[source, graphql, indent=0]
----
type MovieAggregateSelection {
    count: Int!
    description: StringAggregateSelectionNullable!
    title: StringAggregateSelectionNonNullable!
}
----

In case we wanted to remove the `description` field from `MovieAggregateSelection`, what we needed to do is change the `onAggregate` value to `false`, as follow:

[source, graphql, indent=0]
----
type Movie {
    title: String!
    description: String @selectable(onRead: false, onAggregate: false)
}
----

=== `@selectable` with Relationships

This directive can be used along with relationship fields. 

From the previous type definitions, the type `Actor` produced is:

[source, graphql, indent=0]
----
type Actor {
  name: String!
  actedIn(where: MovieWhere, options: MovieOptions, directed: Boolean = true): [Movie!]!
  actedInAggregate(where: MovieWhere, directed: Boolean = true): ActorMovieActedInAggregationSelection
  actedInConnection(where: ActorActedInConnectionWhere, first: Int, after: String, directed: Boolean = true, sort: [ActorActedInConnectionSort!]): ActorActedInConnection!
}
----

This means that the `actedIn` field is queryable from the homonymous generated field `actedIn` and the field `actedInConnection`, to avoid that, it's required to use the directive `@selectable`. 

For instance:

[source, graphql, indent=0]
----
type Movie {
    title: String!
    description: String
}

type Actor {
    name: String!
    actedIn: [Movie!]!
        @relationship(type: "ACTED_IN", direction: OUT)
        @selectable(onRead: false, onAggregate: false)
}
----

It will generate the type type `Actor`:

[source, graphql, indent=0]
----
type Actor {
  name: String!
  actedInAggregate(where: MovieWhere, directed: Boolean = true): ActorMovieActedInAggregationSelection
}
----

[NOTE]
====
Please note how the `actedInAggregate` is not affected by the argument `onAggregate`. To disable the generation of `actedInAggregate` see the `aggregate` argument of the directive xref::reference/directives/schema-configuration/field-configuration.adoc#_relationship[`@relationship`]
====

== `@settable`

This directive sets the availability of the input field on creation and update mutations.
It has two arguments:

* **onCreate**: If disabled, this field will not be available on creation operations.
* **onUpdate**: If disabled, this field will not be available on update operations.

=== Definition

[source, graphql, indent=0]
----
"""Instructs @neo4j/graphql to generate this input field for mutation."""
directive @settable(onCreate: Boolean! = true, onUpdate: Boolean! = true) on FIELD_DEFINITION
----

==== Usage

With this definition:

[source, graphql, indent=0]
----
type Movie {
    title: String!
    description: String @settable(onCreate: true, onUpdate: false)
}

type Actor {
    name: String!
    actedIn: [Movie!]!
        @relationship(type: "ACTED_IN", direction: OUT)
}
----

The following input fields will be generated:

[source, graphql, indent=0]
----
input MovieCreateInput {
    description: String
    title: String!
}

input MovieUpdateInput {
    title: String
}
----

This means the description can be set on creation, but it will not be available on update operations.

=== `@settable` with Relationships

This directive can be used along with relationship fields. 
When an operation on a field is disabled this way, that relationship will not be available on top-level operations. 
For example:

[source, graphql, indent=0]
----
type Movie {
    title: String!
    description: String
}

type Actor {
    name: String!
    actedIn: [Movie!]!
        @relationship(type: "ACTED_IN", direction: OUT)
        @settable(onCreate: false, onUpdate: true)
}
----

The following input fields will be generated:

[source, graphql, indent=0]
----
input ActorCreateInput {
  name: String!
}

input ActorUpdateInput {
  name: String
  actedIn: [ActorActedInUpdateFieldInput!]
}
----

This means the `actedIn` can be updated on an update, but it will not be available on create operations.

== `@readonly` label:deprecated[]

With this directive, fields will only be featured in mutations for creating and in object types for querying.
It is not mutable after creation.

[NOTE]
====
This directive is deprecated. 
Use the xref::reference/directives/schema-configuration/field-configuration.adoc#_settable[`@settable`] directive instead.
====


=== Definition

[source, graphql, indent=0]
----
"""Instructs @neo4j/graphql to only include a field in generated input type for creating, and in the object type within which the directive is applied."""
directive @readonly on FIELD_DEFINITION
----


== `@writeonly` label:deprecated[]

With this directive, fields will only be featured in input types and will not be available for querying the object type through a Query or through a mutation response.

[NOTE]
====
This directive is deprecated. 
Use the xref::reference/directives/schema-configuration/field-configuration.adoc#_selectable[`@selectable`] directive instead.
====


=== Definition

[source, graphql, indent=0]
----
"""Instructs @neo4j/graphql to only include a field in the generated input types for the object type within which the directive is applied, but exclude it from the object type itself."""
directive @writeonly on FIELD_DEFINITION
----
