[[type-definitions-schema-configuration]]
= Schema Configuration

Neo4j GraphQL Library supports several functionalities such as CRUD operations, aggregation, filtering, and others.
To make them work, a large amount of GraphQL types are generated.

In some cases, it may be advisable to reduce the scope of the API produced. 
This section provides information on how to limit access to unwanted operations and reduce the size of the schema which can improve the performance.

For instance, starting from the type definitions:

[source, graphql, indent=0]
----
type Movie { 
    title: String
    length: Int
} 
----

If you want to prevent users from querying `movies` in the Neo4j Database, you need to make the following the changes:

[source, graphql, indent=0]
----
type Movie @query(read: false, aggregate: false) { 
    title: String
    length: Int
} 
----

With this change, the library does **not** generate the following operation fields from the `Query` type:

* `movies`
* `moviesAggregate`
* `moviesConnection`

[NOTE]
====
Aggregations will no longer be generated by default in the 4.0.0 version of the library. See xref:migration/v4-migration.adoc#opt-in-aggregation[`Opt-in Aggregation`] for more information.
====
