[[schema-configuration-type-configuration]]
= Type Configuration

When representing a Neo4j Node, a GraphQL Object type produces multiple operation fields in the `Query`, `Mutation`, and `Subscription` types. 
For example:

[source, graphql, indent=0]
----
type Movie { 
    title: String 
    length: Int
}
----

From these type definitions, the library generates the following operation fields:

**Query**:

    * `movies`
    * `moviesAggregate`
    * `moviesConnection`

**Mutation**:

    * `createMovies`
    * `deleteMovies`
    * `updateMovies`

**Subscription**:

    * `movieCreated`
    * `movieUpdated`
    * `movieDeleted`
.

This section explains how to reduce the operation fields produced using the directives `@query`, `@mutation`, and `@subscription`.

== `@query`

This directive is used to limit the availability of query operations in the library.

=== Definition

[source, graphql, indent=0]
----
directive @query(read: Boolean! = true, aggregate: Boolean! = false) on OBJECT | SCHEMA
----

[NOTE]
====
Aggregations will no longer be generated by default in the 4.0.0 version of the library. 
See xref:migration/v4-migration.adoc#opt-in-aggregation[`Opt-in Aggregation`] for more information.
====

=== Usage

==== Disable _movies_ and _moviesConnection_ operations

[source, graphql, indent=0]
----
type Movie @query(read: false, aggregate: true) { 
    title: String 
    length: Int
}
----

==== Disable _moviesAggregate_ operations

[source, graphql, indent=0]
----
type Movie @query(read: true, aggregate: false)  { 
    title: String 
    length: Int
}
----

== `@mutation`

This directive is used to limit the availability of Mutation operations in the library.

=== Definition

[source, graphql, indent=0]
----
enum MutationFields {
    CREATE
    UPDATE
    DELETE
}

directive @mutation(operations: [MutationFields!]! = [CREATE, UPDATE, DELETE]) on OBJECT | SCHEMA
----

=== Usage

==== Disable Create, Delete, and Update operations for _Movie_

[source, graphql, indent=0]
----
type Movie @mutation(operations: []) { 
    title: String 
    length: Int
}
----

==== Enable only Create operations for _Movie_

[source, graphql, indent=0]
----
type Movie @mutation(operations: [CREATE]) { 
    title: String 
    length: Int
}
----

== `@subscription`

This directive is used to limit Subscription operations in the library.

=== Definition

[source, graphql, indent=0]
----
enum SubscriptionFields {
    CREATE
    UPDATE
    DELETE
    CREATE_RELATIONSHIP
    DELETE_RELATIONSHIP
}

directive @subscription(operations: [SubscriptionFields!]! = [CREATE, UPDATE, DELETE, CREATE_RELATIONSHIP, DELETE_RELATIONSHIP]) on OBJECT | SCHEMA
----

=== Usage

==== Disable subscriptions for _Movie_

[source, graphql, indent=0]
----
type Movie @subscription(operations: [])  { 
    title: String 
    length: Int
}
----

==== Enable only _movieCreated_ subscription for _Movie_

[source, graphql, indent=0]
----
type Movie @subscription(operations: [CREATE]) { 
    title: String 
    length: Int
}
----

== `@exclude` label:deprecated[]

This directive skips the generation of queries and/or subscriptions and/or particular/all mutations for the specified type.

[NOTE]
====
This directive is deprecated.

Use the xref:reference/directives/schema-configuration/type-configuration.adoc#_query[`@query`], xref:reference/directives/schema-configuration/type-configuration.adoc#_mutation[`@mutation`] and the xref:reference/directives/schema-configuration/type-configuration.adoc#_subscription[`@subscription`] directives instead.
====

=== Definition

[source, graphql, indent=0]
----
enum ExcludeOperation {
    CREATE
    READ
    UPDATE
    DELETE
    SUBSCRIBE
}

"""Instructs @neo4j/graphql to exclude the specified operations from query, mutation and subscription generation. If used without an argument, no queries, mutations or subscriptions will be generated for this type."""
directive @exclude(
    operations: [ExcludeOperation!]! = [CREATE, READ, UPDATE, DELETE, SUBSCRIBE]
) on OBJECT
----

=== Usage

==== Disable Query field generation

[source, graphql, indent=0]
----
type User @exclude(operations: [READ]) {
    name: String
}
----

==== Disable single Mutation field generation

[source, graphql, indent=0]
----
type User @exclude(operations: [CREATE]) {
    name: String
}
----

==== Disable multiple Mutation field generation

[source, graphql, indent=0]
----
type User @exclude(operations: [CREATE, DELETE]) {
    name: String
}
----

==== Disable Subscription field generation

[source, graphql, indent=0]
----
type User @exclude(operations: [SUBSCRIBE]) {
    name: String
}
----

==== Disable all Query, Mutation, and Subscription field generation

The following two type definitions are equivalent in the sense that no queries, mutations, or subscriptions will be generated for either of them:

[source, graphql, indent=0]
----
type User @exclude {
    name: String
}
----

[source, graphql, indent=0]
----
type User @exclude(operations: [CREATE, READ, UPDATE, DELETE, SUBSCRIBE]) {
    name: String
}
----