/*
 * Copyright (c) "Neo4j"
 * Neo4j Sweden AB [http://neo4j.com]
 *
 * This file is part of Neo4j.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type { ConcreteEntityAdapter } from "../../../../schema-model/entity/model-adapters/ConcreteEntityAdapter";
import type { RelationshipAdapter } from "../../../../schema-model/relationship/model-adapters/RelationshipAdapter";
import type { Neo4jGraphQLTranslationContext } from "../../../../types/neo4j-graphql-translation-context";
import { asArray, isRecord } from "../../../../utils/utils";
import { ConnectOperation } from "../../ast/operations/ConnectOperation";
import { NodeSelectionPattern } from "../../ast/selection/SelectionPattern/NodeSelectionPattern";
import type { QueryASTFactory } from "../QueryASTFactory";
import { ParamInputField } from "../../ast/input-fields/ParamInputField";
import { raiseAttributeAmbiguity } from "../../utils/raise-attribute-ambiguity";

export class ConnectFactory {
    private queryASTFactory: QueryASTFactory;

    constructor(queryASTFactory: QueryASTFactory) {
        this.queryASTFactory = queryASTFactory;
    }

    public createConnectOperation(
        entity: ConcreteEntityAdapter,
        relationship: RelationshipAdapter,
        input: Record<string, any>[],
        context: Neo4jGraphQLTranslationContext
    ): ConnectOperation {
        // const responseFields = Object.values(
        //     resolveTree.fieldsByTypeName?.[entity.operations.mutationResponseTypeNames.connect] ?? {}
        // );

        const { whereArg } = this.parseConnectArgs(input, false); //connectArg

        const nodeFilters = this.queryASTFactory.filterFactory.createNodeFilters(entity, whereArg.node);
        const connectOP = new ConnectOperation({
            target: entity,
            selectionPattern: new NodeSelectionPattern({
                target: entity,
            }),
            filters: nodeFilters,
            relationship,
        });
        // createConnectionPredicates

        // const projectionFields = responseFields
        //     .filter((f) => f.name === entity.plural)
        //     .map((field) => {
        //         const readOP = this.queryASTFactory.operationsFactory.createReadOperation({
        //             entityOrRel: entity,
        //             resolveTree: field,
        //             context,
        //         }) as ReadOperation;
        //         return readOP;
        //     });

        // connectOP.addProjectionOperations(projectionFields);

        this.hydrateConnectOperation({
            target: entity,
            relationship,
            input,
            connect: connectOP,
            context,
        });
        return connectOP;
    }

    private hydrateConnectOperation({
        target,
        relationship,
        input,
        connect,
        // callbackBucket,
        context,
    }: {
        target: ConcreteEntityAdapter;
        relationship: RelationshipAdapter;
        input: Record<string, any>[];
        connect: ConnectOperation;
        // callbackBucket: CallbackBucket;
        context: Neo4jGraphQLTranslationContext;
    }) {
        // TODO: there is no need to get always the autogenerated field as these are static fields and can be cached
        // [target, relationship].forEach((t) => {
        //     return this.addAutogeneratedFields({
        //         target: t,
        //         unwindCreate: create,
        //     });
        // });

        asArray(input).forEach((inputItem) => {
            raiseAttributeAmbiguity(Object.keys(this.getInputEdge(inputItem)), relationship);
            const targetInputEdge = this.getInputEdge(inputItem);
            for (const key of Object.keys(targetInputEdge)) {
                const attribute = relationship.attributes.get(key);
                if (attribute) {
                    const attachedTo = "relationship";

                    const paramInputField = new ParamInputField({
                        attachedTo,
                        attribute,
                        inputValue: targetInputEdge[key],
                    });
                    connect.addField(paramInputField, attachedTo);
                }
            }
        });

        // this.addPopulatedByFieldToCreate({
        //     entity: target,
        //     create,
        //     input,
        //     callbackBucket,
        //     isNested,
        //     relationship,
        // });
    }

    private getInputNode(inputItem: Record<string, any>, isNested: boolean): Record<string, any> {
        if (isNested) {
            return inputItem.node ?? {};
        }
        return inputItem;
    }

    private getInputEdge(inputItem: Record<string, any>): Record<string, any> {
        return inputItem.edge ?? {};
    }

    // private addAutogeneratedFields({
    //     target,
    //     unwindCreate,
    // }: {
    //     target: ConcreteEntityAdapter | RelationshipAdapter | undefined;
    //     unwindCreate: UnwindCreateOperation | CreateOperation;
    // }): void {
    //     if (!target) {
    //         return;
    //     }
    //     const attachedTo = isConcreteEntity(target) ? "node" : "relationship";
    //     const autoGeneratedFields = getAutogeneratedFields(target);

    //     autoGeneratedFields.forEach((field) => {
    //         if (unwindCreate.getField(field.name, attachedTo)) {
    //             return;
    //         }
    //         unwindCreate.addField(field, attachedTo);
    //     });
    // }

    private parseConnectArgs(
        args: Record<string, any>,
        isTopLevel: boolean
    ): {
        whereArg: { node: Record<string, any>; edge: Record<string, any> };
        connectArg: Record<string, any>;
    } {
        let whereArg;
        const rawWhere = isRecord(args.where) ? args.where : {};
        if (isTopLevel) {
            whereArg = { node: rawWhere.node ?? {}, edge: rawWhere.edge ?? {} };
        } else {
            whereArg = { node: rawWhere.node, edge: {} };
        }
        const connectArg = isRecord(args.connect) ? args.connect : {};
        return { whereArg, connectArg };
    }
}
