/*
 * Copyright (c) "Neo4j"
 * Neo4j Sweden AB [http://neo4j.com]
 *
 * This file is part of Neo4j.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type { ConcreteEntityAdapter } from "../../../../schema-model/entity/model-adapters/ConcreteEntityAdapter";
import type { InterfaceEntityAdapter } from "../../../../schema-model/entity/model-adapters/InterfaceEntityAdapter";
import type { UnionEntityAdapter } from "../../../../schema-model/entity/model-adapters/UnionEntityAdapter";
import type { RelationshipAdapter } from "../../../../schema-model/relationship/model-adapters/RelationshipAdapter";
import type { Neo4jGraphQLTranslationContext } from "../../../../types/neo4j-graphql-translation-context";
import { asArray } from "../../../../utils/utils";
import type { Filter } from "../../ast/filters/Filter";
import { MutationOperationField } from "../../ast/input-fields/MutationOperationField";
import { ParamInputField } from "../../ast/input-fields/ParamInputField";
import { CompositeConnectOperation } from "../../ast/operations/composite/CompositeConnectOperation";
import { CompositeConnectPartial } from "../../ast/operations/composite/CompositeConnectPartial";
import { ConnectOperation } from "../../ast/operations/ConnectOperation";
import { NodeSelectionPattern } from "../../ast/selection/SelectionPattern/NodeSelectionPattern";
import { isConcreteEntity } from "../../utils/is-concrete-entity";
import { isInterfaceEntity } from "../../utils/is-interface-entity";
import { raiseAttributeAmbiguity } from "../../utils/raise-attribute-ambiguity";
import type { QueryASTFactory } from "../QueryASTFactory";

export class ConnectFactory {
    private queryASTFactory: QueryASTFactory;

    constructor(queryASTFactory: QueryASTFactory) {
        this.queryASTFactory = queryASTFactory;
    }

    public createConnectOperation(
        entity: ConcreteEntityAdapter, // TODO: DO we need entity and relationship?
        relationship: RelationshipAdapter,
        input: Record<string, any>[],
        context: Neo4jGraphQLTranslationContext
    ): ConnectOperation {
        // NESTED CONNECT

        const connectOP = new ConnectOperation({
            target: entity,
            selectionPattern: new NodeSelectionPattern({
                target: entity,
            }),
            relationship,
        });

        this.hydrateConnectOperation({
            target: entity,
            relationship,
            input,
            connect: connectOP,
            context,
        });
        return connectOP;
    }

    public createCompositeConnectOperation(
        entity: InterfaceEntityAdapter | UnionEntityAdapter,
        relationship: RelationshipAdapter,
        input: Record<string, any>[],
        context: Neo4jGraphQLTranslationContext
    ): CompositeConnectOperation {
        const partials: CompositeConnectPartial[] = [];
        for (const concreteEntity of entity.concreteEntities) {
            const partial = this.createCompositeConnectPartial(concreteEntity, relationship, input, context);
            partials.push(partial);
        }

        return new CompositeConnectOperation({
            partials,
        });
    }

    private createCompositeConnectPartial(
        entity: ConcreteEntityAdapter,
        relationship: RelationshipAdapter,
        input: Record<string, any>[],
        context: Neo4jGraphQLTranslationContext
    ): CompositeConnectPartial {
        const connectOP = new CompositeConnectPartial({
            target: entity,
            selectionPattern: new NodeSelectionPattern({
                target: entity,
            }),
            relationship,
        });

        this.hydrateConnectOperation({
            target: entity,
            relationship,
            input,
            connect: connectOP,
            context,
        });
        return connectOP;
    }

    private hydrateConnectOperation({
        target,
        relationship,
        input,
        connect,
        // callbackBucket,
        context,
    }: {
        target: ConcreteEntityAdapter;
        relationship: RelationshipAdapter;
        input: Record<string, any>[];
        connect: ConnectOperation;
        // callbackBucket: CallbackBucket;
        context: Neo4jGraphQLTranslationContext;
    }) {
        // TODO: there is no need to get always the autogenerated field as these are static fields and can be cached
        // [target, relationship].forEach((t) => {
        //     return this.addAutogeneratedFields({
        //         target: t,
        //         unwindCreate: create,
        //     });
        // });
        asArray(input).forEach((inputItem) => {
            const { whereArg, connectArg } = this.parseConnectArgs(inputItem); //connectArg
            const nodeFilters: Filter[] = [];
            if (whereArg.node) {
                if (isConcreteEntity(relationship.target)) {
                    nodeFilters.push(...this.queryASTFactory.filterFactory.createNodeFilters(target, whereArg.node));
                } else if (isInterfaceEntity(relationship.target)) {
                    nodeFilters.push(
                        ...this.queryASTFactory.filterFactory.createInterfaceNodeFilters({
                            entity: relationship.target,
                            targetEntity: target,
                            whereFields: whereArg.node,
                            relationship,
                        })
                    );
                }
            }

            connect.addFilters(...nodeFilters);

            asArray(connectArg).forEach((nestedConnectInputFields) => {
                Object.entries(nestedConnectInputFields).forEach(([key, value]) => {
                    const nestedRelationship = target.relationships.get(key);
                    if (!nestedRelationship) {
                        throw new Error("Expected relationship on connect operation. Please contact support");
                    }

                    const nestedEntity = nestedRelationship.target;

                    asArray(value).forEach((nestedConnectInputItem) => {
                        // TODO: Can we ask directly to this.createConnectOperation?
                        const nestedConnectOperation = this.queryASTFactory.operationsFactory.createConnectOperation(
                            nestedEntity,
                            nestedRelationship,
                            nestedConnectInputItem,
                            context
                        );

                        const mutationOperationField = new MutationOperationField(key, nestedConnectOperation);
                        connect.addField(mutationOperationField, "node");
                    });
                });
            });

            const targetInputEdge = this.getInputEdge(inputItem, relationship);

            // Needs to be parsed
            /* Create the attributes for the edge */
            raiseAttributeAmbiguity(Object.keys(targetInputEdge), relationship);
            for (const key of Object.keys(targetInputEdge)) {
                const attribute = relationship.attributes.get(key);
                if (attribute) {
                    const attachedTo = "relationship";

                    const paramInputField = new ParamInputField({
                        attachedTo,
                        attribute,
                        inputValue: targetInputEdge[key],
                    });
                    connect.addField(paramInputField, attachedTo);
                }
            }
        });

        // this.addPopulatedByFieldToCreate({
        //     entity: target,
        //     create,
        //     input,
        //     callbackBucket,
        //     isNested,
        //     relationship,
        // });
    }

    private getInputNode(inputItem: Record<string, any>, isNested: boolean): Record<string, any> {
        if (isNested) {
            return inputItem.node ?? {};
        }
        return inputItem;
    }

    private getInputEdge(inputItem: Record<string, any>, relationship: RelationshipAdapter): Record<string, any> {
        const edge = inputItem.edge ?? {};

        // Deals with composite relationships
        if (relationship.propertiesTypeName && edge[relationship.propertiesTypeName]) {
            return edge[relationship.propertiesTypeName];
        }

        return edge;
    }

    // private addAutogeneratedFields({
    //     target,
    //     unwindCreate,
    // }: {
    //     target: ConcreteEntityAdapter | RelationshipAdapter | undefined;
    //     unwindCreate: UnwindCreateOperation | CreateOperation;
    // }): void {
    //     if (!target) {
    //         return;
    //     }
    //     const attachedTo = isConcreteEntity(target) ? "node" : "relationship";
    //     const autoGeneratedFields = getAutogeneratedFields(target);

    //     autoGeneratedFields.forEach((field) => {
    //         if (unwindCreate.getField(field.name, attachedTo)) {
    //             return;
    //         }
    //         unwindCreate.addField(field, attachedTo);
    //     });
    // }

    private parseConnectArgs(args: Record<string, any>): {
        whereArg: { node: Record<string, any>; edge: Record<string, any> };
        connectArg: Record<string, any>[];
    } {
        const rawWhere = args.where ?? {};

        const whereArg = { node: rawWhere.node, edge: {} };
        const connectArg = args.connect ?? {};
        return { whereArg, connectArg };
    }
}
