/*
 * Copyright (c) "Neo4j"
 * Neo4j Sweden AB [http://neo4j.com]
 *
 * This file is part of Neo4j.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type { ResolveTree } from "graphql-parse-resolve-info";
import type { ConcreteEntityAdapter } from "../../../../schema-model/entity/model-adapters/ConcreteEntityAdapter";
import type { Neo4jGraphQLTranslationContext } from "../../../../types/neo4j-graphql-translation-context";
import type { ReadOperation } from "../../ast/operations/ReadOperation";
import { UpdateOperation } from "../../ast/operations/UpdateOperation";
import type { QueryASTFactory } from "../QueryASTFactory";
import { NodeSelectionPattern } from "../../ast/selection/SelectionPattern/NodeSelectionPattern";
import type { RelationshipAdapter } from "../../../../schema-model/relationship/model-adapters/RelationshipAdapter";
import type { CallbackBucket } from "../../utils/callback-bucket";
import { getAutogeneratedFields } from "../parsers/get-autogenerated-fields";
import { asArray } from "../../../../utils/utils";
import { OperationField } from "../../ast/fields/OperationField";
import { ParamInputField } from "../../ast/input-fields/ParamInputField";
import { type InputField } from "../../ast/input-fields/InputField";
import type { AttributeAdapter } from "../../../../schema-model/attribute/model-adapters/AttributeAdapter";
import type Cypher from "@neo4j/cypher-builder";
import type { MutationOperator } from "../parsers/parse-mutation-field";
import { parseMutationField } from "../parsers/parse-mutation-field";
import { TopLevelUpdateMutationOperation } from "../../ast/operations/TopLevelUpdateMutationOperation";

export class UpdateFactory {
    private queryASTFactory: QueryASTFactory;

    constructor(queryASTFactory: QueryASTFactory) {
        this.queryASTFactory = queryASTFactory;
    }

    public createUpdateOperation(
        entity: ConcreteEntityAdapter,
        resolveTree: ResolveTree,
        context: Neo4jGraphQLTranslationContext,
        callbackBucket: CallbackBucket
        // ): UpdateOperation {
    ): TopLevelUpdateMutationOperation {
        const rawInput = resolveTree.args.update as Record<string, any>[];
        const input = asArray(rawInput) ?? [];
        console.log("input:", input);
        const updateOperations: UpdateOperation[] = input.map((inputItem) => {
            const updateOperation = new UpdateOperation({
                target: entity,
                selectionPattern: new NodeSelectionPattern({
                    target: entity,
                }),
            });

            this.hydrateUpdateOperation({
                target: entity,
                input: inputItem,
                update: updateOperation,
                callbackBucket,
                context,
            });

            return updateOperation;
        });

        const responseFields = Object.values(
            resolveTree.fieldsByTypeName[entity.operations.mutationResponseTypeNames.update] ?? {}
        );
        // OLD
        // const updateOp = new UpdateOperation({ target: entity });
        // const projectionFields = responseFields
        //     .filter((f) => f.name === entity.plural)
        //     .map((field) => {
        //         const readOP = this.queryASTFactory.operationsFactory.createReadOperation({
        //             entityOrRel: entity,
        //             resolveTree: field,
        //             context,
        //         }) as ReadOperation;
        //         return readOP;
        //     });

        // updateOp.addProjectionOperations(projectionFields);
        // return updateOp;

        const projectionOperations = responseFields
            .filter((f) => f.name === entity.plural)
            .map((field) => {
                const readOP = this.queryASTFactory.operationsFactory.createReadOperation({
                    entityOrRel: entity,
                    resolveTree: field,
                    context,
                }) as ReadOperation;

                const fieldOperation = new OperationField({
                    operation: readOP,
                    alias: field.alias,
                });
                return fieldOperation;
            });

        const topLevelMutation = new TopLevelUpdateMutationOperation({
            updateOperations,
            projectionOperations,
        });
        return topLevelMutation;
    }

    private hydrateUpdateOperation({
        target,
        relationship,
        input,
        update,
        callbackBucket,
        context,
    }: {
        target: ConcreteEntityAdapter;
        relationship?: RelationshipAdapter;
        input: Record<string, any>;
        update: UpdateOperation;
        callbackBucket: CallbackBucket;
        context: Neo4jGraphQLTranslationContext;
    }) {
        // const isNested = Boolean(relationship);
        // TODO: there is no need to get always the autogenerated field as these are static fields and can be cached
        [target, relationship].forEach((t) => {
            if (!t) {
                return;
            }
            const autoGeneratedFields = getAutogeneratedFields(t);

            autoGeneratedFields.forEach((field) => {
                update.addField(field);
            });
        });

        this.addEntityAuthorization({ entity: target, context, operation: update });

        asArray(input).forEach((inputItem) => {
            // const targetInput = this.getInputNode(inputItem, isNested);
            // raiseAttributeAmbiguity(Object.keys(targetInput), target);
            // raiseAttributeAmbiguity(Object.keys(this.getInputEdge(inputItem)), relationship);
            for (const key of Object.keys(inputItem)) {
                const { fieldName, operator } = parseMutationField(key);
                // const nestedRelationship = target.relationships.get(fieldName);
                const nestedRelationship = false;
                const attribute = target.attributes.get(fieldName);
                if (!attribute && !nestedRelationship) {
                    throw new Error(`Transpile Error: Input field ${key} not found in entity ${target.name}`);
                }
                if (attribute) {
                    const paramInputField = this.getInputField(operator, attribute, inputItem[key]);
                    update.addField(paramInputField);

                    this.addAttributeAuthorization({
                        attribute,
                        context,
                        update,
                        entity: target,
                    });
                }
                //  else if (nestedRelationship) {
                //     const nestedEntity = nestedRelationship.target;
                //     const operationInput = inputItem[key] ?? {};

                //     const entityAndNodeInput: Array<
                //         [ConcreteEntityAdapter | InterfaceEntityAdapter, Record<string, any>]
                //     > = [];

                //     if (isUnionEntity(nestedEntity)) {
                //         Object.entries(operationInput).forEach(([entityTypename, input]) => {
                //             const concreteNestedEntity = nestedEntity.concreteEntities.find(
                //                 (e) => e.name === entityTypename
                //             );
                //             if (!concreteNestedEntity) {
                //                 throw new Error("Concrete entity not found in create, please contact support");
                //             }

                //             entityAndNodeInput.push([concreteNestedEntity, input as any]);
                //         });
                //     } else {
                //     entityAndNodeInput.push([nestedEntity, operationInput]);
                //     }

                //     entityAndNodeInput.forEach(([nestedEntity, operationInput]) => {
                //         const nestedCreateInput = operationInput.create;
                //         if (nestedCreateInput) {
                //             console.log(
                //                 "Nested creates",
                //                 nestedEntity,
                //                 nestedCreateInput,
                //                 callbackBucket.callbacks.length
                //             );
                //             // TODO:
                //             // this.createNestedCreateOperation({
                //             //     targetEntity: nestedEntity,
                //             //     relationship: nestedRelationship,
                //             //     input: nestedCreateInput,
                //             //     callbackBucket,
                //             //     context,
                //             //     operation: create,
                //             //     key,
                //             // });
                //         }
                //         // TODO:
                //         // const nestedConnectInput = operationInput.connect;
                //         // if (nestedConnectInput) {
                //         //     asArray(nestedConnectInput).forEach((nestedConnectInputItem) => {
                //         //         const nestedConnectOperation =
                //         //             this.queryASTFactory.operationsFactory.createConnectOperation(
                //         //                 nestedEntity,
                //         //                 nestedRelationship,
                //         //                 nestedConnectInputItem,
                //         //                 context,
                //         //                 callbackBucket
                //         //             );

                //         //         const mutationOperationField = new MutationOperationField(nestedConnectOperation, key);
                //         //         create.addField(mutationOperationField);
                //         //     });
                //         // }
                //     });
                // }
            }
            if (relationship) {
                const targetInputEdge = this.getInputEdge(inputItem);
                for (const key of Object.keys(targetInputEdge)) {
                    const attribute = relationship.attributes.get(key);
                    if (attribute) {
                        const attachedTo = "relationship";

                        const paramInputField = new ParamInputField({
                            attachedTo,
                            attribute,
                            inputValue: targetInputEdge[key],
                        });
                        update.addField(paramInputField);
                    }
                }
            }
        });

        // TODO:
        // this.addPopulatedByFieldToCreate({
        //     entity: target,
        //     create,
        //     input,
        //     callbackBucket,
        //     relationship,
        // });
    }

    private addEntityAuthorization({
        entity,
        context,
        operation,
    }: {
        entity: ConcreteEntityAdapter;
        context: Neo4jGraphQLTranslationContext;
        operation: UpdateOperation;
    }): void {
        const authFilters = this.queryASTFactory.authorizationFactory.createAuthValidateRule({
            entity,
            authAnnotation: entity.annotations.authorization,
            when: "AFTER",
            operations: ["UPDATE"],
            context,
        });
        if (authFilters) {
            operation.addAuthFilters(authFilters);
        }
    }

    private addAttributeAuthorization({
        attribute,
        context,
        update,
        entity,
        conditionForEvaluation,
    }: {
        attribute: AttributeAdapter;
        context: Neo4jGraphQLTranslationContext;
        update: UpdateOperation;
        entity: ConcreteEntityAdapter;
        conditionForEvaluation?: Cypher.Predicate;
    }): void {
        const attributeAuthorization = this.queryASTFactory.authorizationFactory.createAuthValidateRule({
            entity,
            when: "AFTER",
            authAnnotation: attribute.annotations.authorization,
            conditionForEvaluation,
            operations: ["UPDATE"],
            context,
        });
        if (attributeAuthorization) {
            update.addAuthFilters(attributeAuthorization);
        }
    }

    private getInputNode(inputItem: Record<string, any>, isNested: boolean): Record<string, any> {
        if (isNested) {
            return inputItem.node ?? {};
        }
        return inputItem;
    }

    private getInputEdge(inputItem: Record<string, any>): Record<string, any> {
        return inputItem.edge ?? {};
    }

    private getInputField(
        operator: MutationOperator | undefined,
        attribute: AttributeAdapter,
        value: unknown
    ): InputField {
        switch (operator) {
            case "SET":
                return new ParamInputField({
                    attachedTo: "node",
                    attribute,
                    inputValue: value,
                });
            case "INCREMENT":
            case "DECREMENT":
            case "ADD":
            case "SUBTRACT":
            case "DIVIDE":
            case "MULTIPLY":
            case "PUSH":
            case "POP":
            default:
                throw new Error(`Unsupported update operator ${operator} on field ${attribute.name} `);
        }
    }
}
