[[create]]
= Create Subscriptions

Subscriptions to `CREATE` events will listen to newly created nodes. A new event will be triggered for each new node.
The event will contain the node's properties.

NOTE: Only nodes created will trigger this event, new relationships will **not** trigger the event.

== `CREATE` event

A subscription to a type can be made with the top-level subscription `[type]Created`. The subscription will contain the following fields:

* `event`: The event triggering this subscription, in this case it will always be `"CREATE"`.
* `created<typename>`: The properties of the newly created node, only top-level properties, without relationships, are available.
* `timestamp`: The timestamp in which the mutation was made. Note that multiple events may come with the same timestamp if triggered by the same query.

=== Example
Considering the following type definitions:
```graphql
type Movie {
    title: String
    genre: String
}
```

A subscription to any `Movie` created would look like:
```graphql
subscription {
    movieCreated {
        createdMovie {
            title
            genre
        }
        event
        timestamp
    }
}
```
