/*
 * Copyright (c) "Neo4j"
 * Neo4j Sweden AB [http://neo4j.com]
 */

import { GraphQLInt, GraphQLNonNull, type GraphQLResolveInfo } from "graphql";
import type { SchemaComposer } from "graphql-compose";
import type { EntityAdapter } from "../../../schema-model/entity/EntityAdapter";
import { UnionEntityAdapter } from "../../../schema-model/entity/model-adapters/UnionEntityAdapter";
import { isConcreteEntity } from "../../../translate/queryAST/utils/is-concrete-entity";
import { translateRead } from "../../../translate/translate-read";
import type { Neo4jGraphQLTranslationContext } from "../../../types/neo4j-graphql-translation-context";
import { execute } from "../../../utils";
import getNeo4jResolveTree from "../../../utils/get-neo4j-resolve-tree";
import { makeSortInput } from "../../generation/sort-and-options-input";
import type { Neo4jGraphQLComposedContext } from "../composition/wrap-query-and-mutation";

export function findResolver({
    entityAdapter,
    composer,
    isLimitRequired,
}: {
    entityAdapter: EntityAdapter;
    composer: SchemaComposer;
    isLimitRequired: boolean | undefined;
}) {
    async function resolve(_root: any, args: any, context: Neo4jGraphQLComposedContext, info: GraphQLResolveInfo) {
        const resolveTree = getNeo4jResolveTree(info, { args });

        (context as Neo4jGraphQLTranslationContext).resolveTree = resolveTree;
        // for composite entities we don't use "this" as varName but we use an autogenerated variable
        let varName;
        if (isConcreteEntity(entityAdapter)) {
            varName = "this";
        }
        const { cypher, params } = translateRead({
            context: context as Neo4jGraphQLTranslationContext,
            entityAdapter,
            varName,
        });
        const executeResult = await execute({
            cypher,
            params,
            defaultAccessMode: "READ",
            context,
            info,
        });

        return executeResult.records.map((x) => x.this);
    }

    const extraArgs = {};

    const whereArgumentType = entityAdapter.operations.whereInputTypeName;
    const args = {
        where: whereArgumentType,
        limit: isLimitRequired ? new GraphQLNonNull(GraphQLInt) : GraphQLInt,
        offset: GraphQLInt,
        ...extraArgs,
    };
    if (!(entityAdapter instanceof UnionEntityAdapter)) {
        const sortConfig = makeSortInput({ entityAdapter, userDefinedFieldDirectives: new Map(), composer });
        if (sortConfig) {
            args["sort"] = sortConfig.NonNull.List;
        }
    }

    return {
        type: `[${entityAdapter.name}!]!`,
        resolve,
        args,
    };
}
