[[type-definitions-unions-and-interfaces]]
= Unions and Interfaces

Unions and interfaces are abstract GraphQL types that enable a schema field to return one of multiple object types.

== Union type
Neo4j GraphQL supports the use of Unions on a `@relationship` field.

=== Example
The following schema defines a `User` type, that has a relationship(`HAS_CONTENT`), of type `[Content]`. `Content` is of type `union` representing either `Blog` or `Post`. 

[source, graphql]
----
union Content = Blog | Post

type Blog {
  title: String
  posts: [Post] @relationship(type: "HAS_POST", direction: OUT)
}

type Post {
  content: String
}

type User {
  name: String
  content: [Content] @relationship(type: "HAS_CONTENT", direction: OUT)
}
----


=== Querying a union
The below query gets the user and their content; 

[source, graphql]
----
query GetUsersWithContent {
  users {
    name
    content {
        ... on Blog {
            title
            posts {
                content
            }
        }
        ... on Post {
            content
        }
    }
  }
}
----

=== Creating a union
The below mutation creates the user and their content; 

[source, graphql]
----
mutation CreateUserAndContent {
  createUsers(
    input: [
      {
        name: "Dan"
        content_Blog: {
          create: [
            {
              title: "My Cool Blog"
              posts: { create: [{ content: "My Cool Post" }] }
            }
          ]
        }
      }
    ]
  ) {
    users {
      name
    }
  }
}

----


== Interface type

Using the interface type will give you no real database support therefor no; query, update, delete, filter support. But instead used as a language feature to safeguard your schema. Great for When dealing with repetitive or large schemas you can essentially put "The side railings up".