version: "3"

services:
  testneo4j:
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/test
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs
      - $HOME/neo4j/import:/var/lib/neo4j/import
      - $HOME/neo4j/plugins:/plugins

  integration:
    build:
      context: ../../
      dockerfile: ./packages/graphql/Dockerfile.integration.test
    depends_on:
      - testneo4j
    environment:
      - NEO_USER=neo4j
      - NEO_PASSWORD=test
      - NEO_URL=bolt://host.docker.internal:7687/neo4j
      - NEO_WAIT=10000
