version: '3.5'
# This is just for local testing
services:
    rabbitmq:
        image: rabbitmq:3.12-management@sha256:c155c8e232586095c20f699800a5586844c19ad9d4304b5f63367ab096076644
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest

    qpid:
        build:
            context: ./qpid-docker
        image: qpid
        ports:
            - "5672:5672"
            - "8080:8080"
