version: '3.5'
# This is just for local testing
services:
    rabbitmq:
        image: rabbitmq:3.12-management@sha256:70b733e4ddaa140904fbe2e5b2d9eb6ab853d229625d9fd388c692915452ced8
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest

    qpid:
        build:
            context: ./qpid-docker
        image: qpid
        ports:
            - "5672:5672"
            - "8080:8080"
