version: '3.5'
# This is just for local testing
services:
    rabbitmq:
        image: rabbitmq:3.12-management@sha256:a44ba5a23397c3d84f8639f1adc037555541877df8fd370ef460133548e21b36
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest

    qpid:
        build:
            context: ./qpid-docker
        image: qpid
        ports:
            - "5672:5672"
            - "8080:8080"
