version: '3.5'
# This is just for local testing
services:
    rabbitmq:
        image: rabbitmq:3.13-management@sha256:0075a575142476ee9ef6ea8216c02cdb49dbbd96d460e11be81c4a2a1ee386b9
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest

    qpid:
        build:
            context: ./qpid-docker
        image: qpid
        ports:
            - "5672:5672"
            - "8080:8080"
