version: '3.5'
# This is just for local testing
services:
    rabbitmq:
        image: rabbitmq:3.13-management@sha256:fb3ee4a8ec76a7ba1662f64218f9279cd8c2de4385fa5df791a2496129437751
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest

    qpid:
        build:
            context: ./qpid-docker
        image: qpid
        ports:
            - "5672:5672"
            - "8080:8080"
