version: '3.5'
# This is just for local testing
services:
    rabbitmq:
        image: rabbitmq:3.13-management@sha256:9d984edac52ffeea602dd20e28b752394597ad214dcce5f66c1bd45700c8f296
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest

    qpid:
        build:
            context: ./qpid-docker
        image: qpid
        ports:
            - "5672:5672"
            - "8080:8080"
