version: '3.5'
# This is just for local testing
services:
    rabbitmq:
        image: rabbitmq:3.13-management@sha256:6f4ecd26acdac1e58d50928d12926e6a04f0dccb76d772f278243d85fb57e7a9
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest

    qpid:
        build:
            context: ./qpid-docker
        image: qpid
        ports:
            - "5672:5672"
            - "8080:8080"
