[[migration-guide-server]]
= Server

[[migration-guide-server-schema-generation]]
== Schema Generation

In your server codebase, the process of creating an executable schema has changed. For a simple application, what used to be:

[source, javascript, indent=0]
----
import { makeAugmentedSchema } from "neo4j-graphql-js";

import typeDefs from "./type-definitions";

const schema = makeAugmentedSchema({ typeDefs });
----

Has become:

[source, javascript, indent=0]
----
import { makeAugmentedSchema } from "neo4j-graphql-js";

import typeDefs from "./type-definitions";

const neo4jGraphQL = new Neo4jGraphQL({ typeDefs });

const schema = await neo4jGraphQL.getSchema();
----

Additionally, the `Neo4jGraphQL` constructor allows you to pass in a driver instance instead of passing one in the context of each request.

=== Schema Configuration

The `neo4j-graphql-js` library would allow a user to configure the GraphQL schema via the `makeAugmentedSchema()` function.

For example, to exclude all queries and all mutations:

[source, javascript, indent=0]
----
const schema = makeAugmentedSchema({
  typeDefs,
  config: {
    query: false, // exclude all queries
    mutation: false // exclude all mutations
  }
});
----

Or to exclude queries for a specific type like so:

[source, javascript, indent=0]
----
const schema = makeAugmentedSchema({
  typeDefs,
  config: {
    query: {
      exclude: ["NameOfTypeToExclude"] // exclude query for type NameOfTypeToExclude
    },
    mutation: false // exclude all mutations
  }
});
----

To achieve the same behaviour with the new `@neo4j/graphql` library, the GraphQL schema has to be extended instead. Note, no additional configuration or parameters need to be passed to the `getSchema()` function.

To exclude all mutations for a specific type:
[source, graphql, indent=0]
----
type NameOfType @exclude(operations: [CREATE, UPDATE, DELETE]) {
  name: String
}
----

Or to exclude all queries and all mutations for a specific type like so:

[source, graphql, indent=0]
----
type NameOfTypeToExclude @exclude {
  name: String
}
----
For more information regarding the above used `@exclude` directive, see xref::type-definitions/access-control.adoc#type-definitions-access-control-exclude[`@exclude`].


== Database Configuration

=== Driver

Once a schema has been generated, it can be passed into a GraphQL server instance with the driver in the context, identical to using the old library. For example, using Apollo Server and using the schema generated above:

[source, javascript, indent=0]
----
import { ApolloServer } from "@apollo/server";
import { startStandaloneServer } from "@apollo/server/standalone";

import driver from "./driver";
import schema from "./schema";

const server = new ApolloServer({ schema });

const { url } = await startStandaloneServer(server, {
    context: async ({ req }) => ({ driver, token: req.headers.token }),
});

console.log(`@neo4j/graphql API ready at ${url}`);
----

=== Multiple Databases

Multiple databases were supported in `neo4j-graphql-js` by passing a context key `neo4jDatabase` with the name of a database, for example for database called "sanmateo":

[source, javascript, indent=0]
----
import { ApolloServer } from "@apollo/server";
import { startStandaloneServer } from "@apollo/server/standalone";

import driver from "./driver";
import schema from "./schema";

const server = new ApolloServer({ schema });

const { url } = await startStandaloneServer(server, {
    context: async ({ req }) => ({ driver, neo4jDatabase: "sanmateo", token: req.headers.token }),
});

console.log(`@neo4j/graphql API ready at ${url}`);
----

In `@neo4j/graphql`, this has now become:

[source, javascript, indent=0]
----
import { ApolloServer } from "@apollo/server";
import { startStandaloneServer } from "@apollo/server/standalone";

import driver from "./driver";
import schema from "./schema";

const server = new ApolloServer({ schema, context: { driver, driverConfig: { database: "sanmateo" } } });

const { url } = await startStandaloneServer(server, {
    context: async ({ req }) => ({ token: req.headers.token }),
});

console.log(`@neo4j/graphql API ready at ${url}`);
----

Database bookmarks are also supported. See xref::driver-configuration.adoc[Driver Configuration] for more information.
