/*
 * Copyright (c) "Neo4j"
 * Neo4j Sweden AB [http://neo4j.com]
 */

import { Neo4jGraphQL } from "../../../src";
import { formatCypher, formatParams, translateQuery } from "../utils/tck-test-utils";

describe("https://github.com/neo4j/graphql/issues/1628", () => {
    let typeDefs: string;
    let neoSchema: Neo4jGraphQL;

    beforeAll(() => {
        typeDefs = /* GraphQL */ `
            type frbr__Work @node(labels: ["frbr__Work", "Resource"]) @mutation(operations: []) {
                """
                IRI
                """
                iri: ID! @alias(property: "uri")
                dcterms__title: [dcterms_title!]! @relationship(type: "dcterms__title", direction: OUT)
            }

            type dcterms_title @node(labels: ["dcterms_title", "property"]) @mutation(operations: []) {
                value: String
            }
        `;

        neoSchema = new Neo4jGraphQL({
            typeDefs,
        });
    });

    test("Filter generated by query doesn't utilise index", async () => {
        const query = /* GraphQL */ `
            {
                frbrWorks(limit: 10000, where: { dcterms__title: { some: { value_CONTAINS: "0777" } } }) {
                    iri
                    dcterms__title(where: { value_CONTAINS: "0777" }) {
                        value
                    }
                }
            }
        `;

        const result = await translateQuery(neoSchema, query);

        expect(formatCypher(result.cypher)).toMatchInlineSnapshot(`
            "CYPHER 5
            MATCH (this:frbr__Work&Resource)
            WHERE EXISTS {
              MATCH (this)-[:dcterms__title]->(this0:dcterms_title&property)
              WHERE this0.value CONTAINS $param0
            }
            WITH *
            LIMIT $param1
            CALL (this) {
              MATCH (this)-[this1:dcterms__title]->(this2:dcterms_title&property)
              WHERE this2.value CONTAINS $param2
              WITH DISTINCT this2
              WITH this2 { .value } AS this2
              RETURN collect(this2) AS var3
            }
            RETURN this { iri: this.uri, dcterms__title: var3 } AS this"
        `);

        expect(formatParams(result.params)).toMatchInlineSnapshot(`
            "{
                \\"param0\\": \\"0777\\",
                \\"param1\\": {
                    \\"low\\": 10000,
                    \\"high\\": 0
                },
                \\"param2\\": \\"0777\\"
            }"
        `);
    });
});
