[[ogm-api-reference-ogm]]
= `OGM`

== `constructor`

Returns an `OGM` instance.

Takes an `input` object as a parameter, which is then passed to the `Neo4jGraphQL` constructor. Supported options are listed in the documentation for xref::api-reference/neo4jgraphql.adoc[`Neo4jGraphQL`].

=== Example

[source, javascript, indent=0]
----
const ogm = new OGM({
    typeDefs,
});
----

== `init`

Asynchronous method to initialize the OGM. Internally, calls xref::api-reference/neo4jgraphql.adoc#api-reference-getschema[`Neo4jGraphQL.getSchema()`] to generate a GraphQL schema, and stores the result. Initializes any models which have been created before this execution, and will throw an error if any of them are invalid.

== `model`

Returns a `Model` instance matching the passed in name, or (if the OGM has been initialized) throws an `Error` if one can't be found.

Accepts a single argument `name` of type `string`.

=== Example

For the following type definitions:

[source, graphql, indent=0]
----
type User {
    username: String!
}
----

The following would successfully return a `Model` instance:

[source, javascript, indent=0]
----
const User = ogm.model("User");
----

The following would throw an `Error`:

[source, javascript, indent=0]
----
const User = ogm.model("NotFound");
----


[[ogm-api-reference-assertconstraints]]
== `assertIndexesAndConstraints`

Asynchronous method to assert the existence of database constraints, that either resolves to `void` in a successful scenario, or throws an error if the necessary constraints do not exist following its execution.

Takes an `input` object as a parameter, the supported fields of which are described below.

=== Example

Given the following type definitions saved to the variable `typeDefs` and a valid driver instance saved to the variable `driver`:

[source, graphql, indent=0]
----
type Book {
    isbn: String! @unique
}
----

And the construction and initialisation of an `OGM`, using:

[source, javascript, indent=0]
----
const ogm = new OGM({
    typeDefs,
});
await ogm.init();
----

The following will check whether a unique node property constraint exists for label "Book" and property "isbn", and throw an error if it does not:

[source, javascript, indent=0]
----
await ogm.assertIndexesAndConstraints();
----

The next example will create the constraint if it does not exist:

[source, javascript, indent=0]
----
await ogm.assertIndexesAndConstraints({ options: { create: true } });
----

[[ogm-api-reference-assertconstraints-input]]
=== Input

Accepts the arguments below:

[cols="1,2,3"]
|===
|Name |Type |Description

|`options`
|xref::ogm/api-reference/ogm.adoc#ogm-api-reference-assertconstraints-input-assertconstraintsoptions[`AssertConstraintsOptions`]
|Options for the execution of `assertIndexesAndConstraints`.
|===


[[ogm-api-reference-assertconstraints-input-assertconstraintsoptions]]
==== `AssertConstraintsOptions`

[cols="1,2,3"]
|===
|Name |Type |Description

|`create`
|`boolean`
|Whether or not to create constraints if they do not yet exist. Disabled by default.
|===
