[[amqp]]
= AMQP Plugin

WARNING: Subscriptions are only available as a beta, its API may change in the future. It is not recommended to use subscriptions in production environments.

The `@neo4j/graphql-plugin-subscriptions-amqp` plugin connects to brokers through `AMQP 0-9-1` protocol such as:

* link:https://www.rabbitmq.com/[RabbitMQ]
* link:https://qpid.apache.org/[Apache Qpid]
* link:https://activemq.apache.org/[Apache ActiveMQ]

It can be installed with npm:

```sh
npm install @neo4j/graphql-plugin-subscriptions-amqp
```

NOTE: AMQP 1.0 is **not** supported by this plugin.

== Usage

```javascript
const Neo4jGraphQLSubscriptionsAMQP = require("@neo4j/graphql-plugin-subscriptions-amqp");

const plugin = new Neo4jGraphQLSubscriptionsAMQP();

await plugin.connect({
    hostname: "localhost",
    username: "guest",
    password: "guest",
});

const neoSchema = new Neo4jGraphQL({
    typeDefs,
    driver,
    plugins: {
        subscriptions: plugin,
    },
});
```

== API
The following options can be passed to the contructor:

* exchange: The exchange to be used in the broker. Defaults to `neo4j.graphql.subscriptions.fx`.
* version: The AMQP version to be used. Currently only `0-9-1` is supported.

=== connect(connectionOptions): Promise<Connection>
Connects to the broker, creating the required exchanges and queues. Returns the Connection.
It accepts a single AMQP url string or an configuration object:

* hostname: Hostname to be used, defaults to `localhost`.
* username: defaults to `guest`.
* password: defaults to `guest`.
* port: Port of the AMQP broker, defaults to `5672`.

Additionally, any option supported by link:https://www.npmjs.com/package/amqplib[amqplib] can be passed to `connect`.


=== close(): Promise<void>
Closes the channel created and unbinds the event emitter. Note that `close` will **not** close the connection to the broker. You must close it
 through the value returned by `connect`.
