= Context population

The request context can be populated with a number of different values to influence the behavior of the Neo4j GraphQL Library.

== `driverConfig`

== `executionContext`

The Neo4j driver, session or transaction which is used to execute the translated query.

== `jwt`

A decoded JWT payload which can be provided for use in Authentication and Authorization.

It takes precedence over `token`, if provided.

For example:

[source, json, indent=0]
----
{
    sub: "1234567890",
    name: "John Doe",
    iat: 1516239022,
}
----

== `neo4jDatabaseInfo`

== `queryOptions`

== `token`

The bearer token to be decoded/verified for use in authentication and authorization.

It can be found in the `Authorization` HTTP header and be provided with or without an authentication scheme.
For example:


[source, plaintext, indent=0]
----
Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
----

In case you do not want to use the authentication scheme, do the following:

[source, plaintext, indent=0]
----
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
----
