[[mathematical-operators]]
= Mathematical operators

On numerical types (`Int`, `Float`, xref::type-definitions/types.adoc#type-definitions-types-bigint[`BigInt`]) Mathematical operators can be used.

== Int/BigInt operators
For Int and Big int types, the following operators are available:

* `_DECREMENT`
* `_INCREMENT`

Using the following type definition:
[source, graphql, indent=0]
----
type Video {
    viewers: Int
}
----

Then, the `viewers` property can be incremented using the following Mutation:
[source, graphql, indent=0]
----
mutation {
    updateVideos(update: { viewers_INCREMENT: 1 }) {
        videos {
            viewers
        }
    }
}
----

== Float operators
For the Float type, the following operators are available:

* `_ADD`
* `_SUBTRACT`
* `_MULTIPLY`
* `_DIVIDE`

Using the following type definition:
[source, graphql, indent=0]
----
type Runner {
    bestTime: Float
}
----

Then, the `bestTime` property can be modified using the following Mutation:
[source, graphql, indent=0]
----
mutation {
    updateRunners(update: { bestTime_SUBTRACT: 0.13 }) {
        runners {
            bestTime
        }
    }
}
----

== Nested update
Mathematical operators are not limited to Node updates but are also available in:

* `Nested Nodes`
* `Relationship properties`
* `Interface properties`

Using the following type definition:
[source, graphql, indent=0]
----
type Movie {
    title: String
    viewers: Int
    actors: [Actor!]! @relationship(type: "ACTED_IN", properties: "ActedIn", direction: IN)
}

type Actor {
    name: String!
    actedIn: [Movie!]! @relationship(type: "ACTED_IN", properties: "ActedIn", direction: OUT)
}

interface ActedIn @relationshipProperties {
    pay: Float
}
----

Then, the `pay` property can be modified using the following Mutation:
[source, graphql, indent=0]
----
mutation Mutation {
    updateActors(
        where: { name: "Keanu Reeves" },
         update: {
            actedIn: [
            {
                update: {
                    edge: {
                        pay_ADD: 1000000
                    }
                }
            }
            ]
        }) {
        actors {
        name
        actedIn {
            title
            viewers
        }
        actedInConnection {
            edges {
                pay
            }
        }
        }
    }
}
----

And to increment the `viewers` property instead:
[source, graphql, indent=0]
----
mutation Mutation {
    updateActors(
        where: { name: "Keanu Reeves" },
        update: {
            actedIn: [
            {
                update: {
                    node: {
                        viewers_INCREMENT: 300
                    }
                }
            }
            ]
        }) {
        actors {
            name
            actedIn {
                title
                 viewers
        }
        actedInConnection {
            edges {
                pay
            }
        }
        }
    }
}
----

== Optional fields
Operators remain available for optional fields, this means that if an operator is been used with fields not yet defined then a GraphQL error is raised.
