/*
 * Copyright (c) "Neo4j"
 * Neo4j Sweden AB [http://neo4j.com]
 */

import Debug from "debug";
import type { GraphQLFieldResolver, GraphQLResolveInfo } from "graphql";
import type { Driver } from "neo4j-driver";
import { Executor } from "../../../classes/Executor";
import type { Neo4jDatabaseInfo } from "../../../classes/Neo4jDatabaseInfo";
import { getNeo4jDatabaseInfo } from "../../../classes/Neo4jDatabaseInfo";
import type { Neo4jGraphQLAuthorization } from "../../../classes/authorization/Neo4jGraphQLAuthorization";
import { DEBUG_GRAPHQL } from "../../../constants";
import { debugGraphQLResolveInfo } from "../../../debug/debug-graphql-resolve-info";
import { debugObject } from "../../../debug/debug-object";
import type { Neo4jGraphQLSchemaModel } from "../../../schema-model/Neo4jGraphQLSchemaModel";
import type { AuthorizationContext, ContextFeatures, FulltextContext, VectorContext } from "../../../types";
import type { Neo4jGraphQLContext } from "../../../types/neo4j-graphql-context";
import { getAuthorizationContext } from "./utils/get-authorization-context";

const debug = Debug(DEBUG_GRAPHQL);

export type WrapResolverArguments = {
    driver?: Driver;
    jwtPayloadFieldsMap?: Map<string, string>;
    schemaModel: Neo4jGraphQLSchemaModel;
    dbInfo?: Neo4jDatabaseInfo;
    features: ContextFeatures;
    authorization?: Neo4jGraphQLAuthorization;
};

/**
 * The type describing the context generated by {@link wrapQueryAndMutation}.
 */
export interface Neo4jGraphQLComposedContext extends Neo4jGraphQLContext {
    schemaModel: Neo4jGraphQLSchemaModel;
    features: ContextFeatures;
    executor: Executor;
    authorization: AuthorizationContext;
    neo4jDatabaseInfo?: Neo4jDatabaseInfo;
    fulltext?: FulltextContext;
    vector?: VectorContext;
    /** When true, the context is being used for translation only (no execution): authentication checks, custom resolvers and populatedBy callbacks are skipped. */
    dryRun?: boolean;
}

let neo4jDatabaseInfo: Neo4jDatabaseInfo;

export const wrapQueryAndMutation =
    ({ driver, jwtPayloadFieldsMap, schemaModel, dbInfo, authorization, features }: WrapResolverArguments) =>
    (next: GraphQLFieldResolver<any, Neo4jGraphQLComposedContext>) =>
    async (root, args, context: Neo4jGraphQLContext, info: GraphQLResolveInfo) => {
        debugGraphQLResolveInfo(debug, info);
        debugObject(debug, "incoming context", context);

        if (!context?.executionContext) {
            if (!driver) {
                throw new Error(
                    "A Neo4j driver instance must either be passed to Neo4jGraphQL on construction, or a driver, session or transaction passed as context.executionContext in each request."
                );
            }
            context.executionContext = driver;
        }

        const authorizationContext = await getAuthorizationContext(context, authorization, jwtPayloadFieldsMap);
        if (!context.jwt) {
            context.jwt = authorizationContext.jwt;
        }

        const executor = new Executor({
            executionContext: context.executionContext,
            cypherQueryOptions: context.cypherQueryOptions,
            sessionConfig: context.sessionConfig,
            cypherParams: context.cypherParams,
            transaction: {
                ...context.transaction,
                metadata: { ...context.transaction?.metadata, ...context.transactionMetadata },
            },
        });

        if (dbInfo) {
            neo4jDatabaseInfo = dbInfo;
        }
        if (!neo4jDatabaseInfo?.version) {
            neo4jDatabaseInfo = await getNeo4jDatabaseInfo(executor);
        }

        const internalContext = {
            schemaModel,
            features,
            executor,
            authorization: authorizationContext,
        };

        const finalContext = {
            // Some TCK tests override this value to generate version-specific Cypher
            neo4jDatabaseInfo,
            ...context,
            ...internalContext,
        };

        return next(root, args, finalContext, info);
    };
