[[type-definitions-database-mapping]]
= Database Mapping

[[type-definitions-alias]]
== `@alias`

This directive maps a GraphQL field to a Neo4j property on a node or relationship.

This can be used on any fields that are not `@cypher` or `@relationship` fields.

=== Definition

[source, graphql, indent=0]
----
"""Indicates that the field is to be mapped to the underlying Neo4j under a different property name."""
directive @alias(property: String!) on FIELD_DEFINITION
----

=== Usage

[source, graphql, indent=0]
----
type User {
    id: ID! @id @alias(property: "dbId")
    username: String!
}
----

[source, graphql, indent=0]
----
type User {
    id: ID! @id
    username: String! @alias(property: "dbUserName")
    livesIn: [City!]! @relationship(direction: OUT, type: "LIVES_IN", properties: "UserLivesInProperties")
}

type City {
    name: String
}

interface UserLivesInProperties @relationshipProperties {
    since: DateTime @alias(property: "moveInDate")
}
----

[[type-definitions-node]]
== `@node`

The `@node` directive is used to specify the configuration of a GraphQL object type which represents a Neo4j node.

=== Definition

[source, graphql, indent=0]
----
"""Informs @neo4j/graphql of node metadata"""
directive @node(
    """Map the GraphQL type to a custom Neo4j node label"""
    label: String
    """Map the GraphQL type to match additional Neo4j node labels"""
    additionalLabels: [String]
) on OBJECT
----

=== Usage
`@node` can be used with the following optional parameters.

==== `label`
The parameter `label` defines the label to be used in Neo4j instead of the GraphQL type name:

[source, graphql, indent=0]
----
type Movie @node(label: "Film") {
    title: String!
}
----

This way, the following query:

[source, graphql, indent=0]
----
{
  movies {
    title
  }
}
----

Generates the cypher query:

[source, cypher, indent=0]
----
MATCH (this: Film)
RETURN this { .title } as this
----

===== Using `$jwt` and `$context`
In some cases, we may want to generate dynamic labels depending on the user requesting. In these cases, we can use the variable `$jwt` to define a custom label define in the JWT (similarly to how it is used in the xref::auth/index.adoc[`@auth` directive]):

[source, graphql, indent=0]
----
type User @node(label: "$jwt.username") {
    name: String!
}
----

The following query will yield a different cypher query depending on the user JWT:

[source, graphql, indent=0]
----
{
  users {
    name
  }
}
----

Assuming an user with the value `"username": "arthur"` in JWT, the Cypher query will look like:

[source, cypher, indent=0]
----
MATCH (this:arthur)
RETURN this { .name } as this
----

Similarly, context values can be passed directly:

[source, graphql, indent=0]
----
type User @node(label: "$context.appId") {
    name: String!
}
----

When running the server with Apollo:
[source, js, indent=0]
----
new ApolloServer({
    schema: neoSchema.schema,
    context: ({ req }) => ({ req, appId: "myApp" }),
});
----

==== `additionalLabels`

`additionalLabels` lets you define extra Neo4j labels that need to exist on the node for that GraphQL type.

[source, graphql, indent=0]
----
type Actor @node(additionalLabels: ["Person", "User"]) {
    name: String!
}
----

The following query:

[source, graphql, indent=0]
----
{
  Actor {
    name
  }
}
----

Generates the following cypher query, with the labels `Actor`, `Person` and `User`:

[source, cypher, indent=0]
----
MATCH (this:Actor:Person:User)
RETURN this { .name } as this
----

Note that `additionalLabels` can be used along with `label`:

[source, graphql, indent=0]
----
type Actor @node(label: "ActorDB", additionalLabels: ["Person"]) {
    name: String!
}
----

In this case, the resulting Cypher query will use the labels `ActorDB` and `Person` instead of `Actor`:

----
MATCH (this:ActorDB:Person)
RETURN this { .name } as this
----
<<#_using_jwt_and_context,Context and JWT variables>> can be used with `additionalLabels` in the same fashion as in `label`:

[source, graphql, indent=0]
----
type User @node(additionalLabels: ["$jwt.username"]) {
    name: String!
}
----

==== `plural`
The parameter `plural` redefines how to compose the plural of the type for the generated operations. This is particularly
useful for types that are not correctly pluralized or are non-English words.

[source, graphql, indent=0]
----
type Tech @node(plural: "Techs") {
  name: String
}
----

This way, instead of the wrongly generated `teches`, the type is properly written as `techs`:

[source, graphql, indent=0]
----
{
  techs {
    title
  }
}
----

The same is applied to other operations such as `createTechs`. Note that database labels will not change.
