[[api-reference-neo4jgraphql]]
= `Neo4jGraphQL`

== `constructor`

Returns a `Neo4jGraphQL` instance.

Takes an `input` object as a parameter, the supported fields of which are described below.

=== Example

[source, javascript, indent=0]
----
const neoSchema = new Neo4jGraphQL({
    typeDefs,
});
----

[[api-reference-neo4jgraphql-input]]
=== Input

Accepts all of the options from https://www.graphql-tools.com/docs/generate-schema#makeexecutableschemaoptions[`makeExecutableSchema`], plus the additional arguments below:

|===
|Name and Type |Description

|`driver` +
 +
 Type: https://neo4j.com/docs/javascript-manual/current/[`Driver`]
|An instance of a Neo4j driver.

|`features` +
 +
 Type: xref::reference/api-reference/neo4jgraphql.adoc#api-reference-neo4jgraphql-input-neo4jfeaturessettings[`Neo4jFeaturesSettings`]
|Could be used for configure/enable/disable specific features. 
|===

[[api-reference-neo4jgraphql-input-neo4jfeaturessettings]]
==== `Neo4jFeaturesSettings`

|===
|Name and Type |Description

|`filters` +
 +
 Type: xref::reference/api-reference/neo4jgraphql.adoc#api-reference-neo4jgraphql-input-neo4jfilterssettings[`Neo4jFiltersSettings`]
|Additional configuration for filters.
|===

[[api-reference-neo4jgraphql-input-neo4jfilterssettings]]
==== `Neo4jFiltersSettings`

|===
|Name and Type |Description

|`String` +
 +
 Type: xref::reference/api-reference/neo4jgraphql.adoc#api-reference-neo4jgraphql-input-neo4jstringfilterssettings[`Neo4jStringFiltersSettings`]
|Additional configuration for String filters.
|`ID` +
 +
 Type: xref::reference/api-reference/neo4jgraphql.adoc#api-reference-neo4jgraphql-input-neo4jidfilterssettings[`Neo4jIDFiltersSettings`]
|Additional configuration for String filters.
|===

[[api-reference-neo4jgraphql-input-neo4jstringfilterssettings]]
==== `Neo4jStringFiltersSettings`

|===
|Name and Type |Description

|`GT` +
 +
 Type: `boolean`
| Enables GT comparator.

|`GTE` +
 +
 Type: `boolean`
| Enables GTE comparator.

|`LT` +
 +
 Type: `boolean`
| Enables LT comparator.

|`LTE` +
 +
 Type: `boolean`
| Enables LTE comparator.

|`MATCHES` +
 +
 Type: `boolean`
| Enables MATCHES comparator.

|===

[[api-reference-neo4jgraphql-input-neo4jidfilterssettings]]
==== `Neo4jIDFiltersSettings`

|===
|Name and Type |Description

|`MATCHES` +
 +
 Type: `boolean`
| Enables MATCHES comparator.

|===

[[api-reference-neo4jgraphql-input-neo4jgraphqlplugins]]
==== `Neo4jGraphQLPlugins`

|===
|Name and Type |Description

|`auth` +
 +
 Type: `Neo4jGraphQLAuthPlugin`
|Plugin slot for auth capabilities.
|===

[[api-reference-getschema]]
== `getSchema`

An asynchronous method that generates the GraphQL schema to be used in a server. The result is memoized, so if this is called twice, the schema is only generated once.

[[api-reference-checkneo4jcompat]]
== `checkNeo4jCompat`

Asynchronous method to check the compatibility of the specified DBMS, that either resolves to `void` in a successful scenario, or throws an error if the database is not compatible with the Neo4j GraphQL Library.

Takes an `input` object as a parameter, the supported fields of which are described below.

=== Example

Given any valid type definitions saved to the variable `typeDefs` and a valid driver instance saved to the variable `driver`, the following will confirm database compatibility:

[source, javascript, indent=0]
----
const neoSchema = new Neo4jGraphQL({ typeDefs, driver });
await neoSchema.checkNeo4jCompat();
----

[[api-reference-checkneo4jcompat-input]]
=== Input

Accepts the arguments below:

|===
|Name and Type |Description

|`driver` +
 +
 Type: https://neo4j.com/docs/javascript-manual/current/[`Driver`]
|An instance of a Neo4j driver.

|`driverConfig` +
 +
 Type: xref::reference/api-reference/neo4jgraphql.adoc#api-reference-checkneo4jcompat-input-driverconfig[`DriverConfig`]
|Additional driver configuration options.
|===

[[api-reference-checkneo4jcompat-input-driverconfig]]
==== `DriverConfig`

|===
|Name and Type |Description

|`database` +
 +
 Type: `string`
|The name of the database within the DBMS to connect to.

|`bookmarks` +
 +
 Type: `string` or `Array<string>`
|One or more bookmarks to use for the connection.
|===

[[api-reference-assertconstraints]]
== `assertIndexesAndConstraints`

Asynchronous method to assert the existence of database constraints, that either resolves to `void` in a successful scenario, or throws an error if the necessary constraints do not exist following its execution.

Takes an `input` object as a parameter, the supported fields of which are described below.

=== Example

Given the following type definitions saved to the variable `typeDefs` and a valid driver instance saved to the variable `driver`:

[source, graphql, indent=0]
----
type Book {
    isbn: String! @unique
}
----

And the construction of a `Neo4jGraphQL`, using:

[source, javascript, indent=0]
----
const neoSchema = new Neo4jGraphQL({ typeDefs, driver });
const schema = await neoSchema.getSchema();
----

The following will check whether a unique node property constraint exists for label "Book" and property "isbn", and throw an error if it does not:

[source, javascript, indent=0]
----
await neoSchema.assertIndexesAndConstraints();
----

The next example will create the constraint if it does not exist:

[source, javascript, indent=0]
----
await neoSchema.assertIndexesAndConstraints({ options: { create: true } });
----

[[api-reference-assertconstraints-input]]
=== Input

Accepts the arguments below:

|===
|Name and Type |Description

|`driver` +
 +
 Type: https://neo4j.com/docs/javascript-manual/current/[`Driver`]
|An instance of a Neo4j driver.

|`driverConfig` +
 +
 Type: xref::reference/api-reference/neo4jgraphql.adoc#api-reference-assertconstraints-input-driverconfig[`DriverConfig`]
|Additional driver configuration options.

|`options` +
 +
 Type: xref::reference/api-reference/neo4jgraphql.adoc#api-reference-assertconstraints-input-assertconstraintsoptions[`AssertConstraintsOptions`]
|Options for the execution of `assertIndexesAndConstraints`.
|===

[[api-reference-assertconstraints-input-driverconfig]]
==== `DriverConfig`

|===
|Name and Type |Description

|`database` +
 +
 Type: `string`
|The name of the database within the DBMS to connect to.

|`bookmarks` +
 +
 Type: `string` or `Array<string>`
|One or more bookmarks to use for the connection.
|===

[[api-reference-assertconstraints-input-assertconstraintsoptions]]
==== `AssertConstraintsOptions`

|===
|Name and Type |Description

|`create` +
 +
 Type: `boolean`
|Whether or not to create constraints if they do not yet exist. Disabled by default.
|===
