[[schema-filtering]]
= Filtering

[cols="h,d,d,d,d,d,d,d,d,d",options=header]
|===
|                  | Int | Float | String | Boolean | ID | BigInt | DateTime | Point | CartesianPoint
|                  | ✓   | ✓     | ✓      | ✓       | ✓  | ✓      | ✓        | ✓     | ✓
| _NOT             | ✓   | ✓     | ✓      | ✓       | ✓  | ✓      | ✓        | ✓     | ✓
| _LT              | ✓   | ✓     |        |         |    | ✓      | ✓        | ✓     | ✓
| _LTE             | ✓   | ✓     |        |         |    | ✓      | ✓        | ✓     | ✓
| _GTE             | ✓   | ✓     |        |         |    | ✓      | ✓        | ✓     | ✓
| _GT              | ✓   | ✓     |        |         |    | ✓      | ✓        | ✓     | ✓
| _CONTAINS        |     |       | ✓      |         | ✓  |        |          |       |
| _NOT_CONTAINS    |     |       | ✓      |         | ✓  |        |          |       |
| _STARTS_WITH     |     |       | ✓      |         | ✓  |        |          |       |
| _NOT_STARTS_WITH |     |       | ✓      |         | ✓  |        |          |       |
| _ENDS_WITH       |     |       | ✓      |         | ✓  |        |          |       |
| _NOT_ENDS_WITH   |     |       | ✓      |         | ✓  |        |          |       |
| _MATCHES*        |     |       | ✓      |         | ✓  |        |          |       |
| _DISTANCE        |     |       |        |         |    |        |          | ✓     | ✓
|===

== Equality operators

All types can be tested for either equality or non-equality. These are only two comparison operators available for the `Boolean` type.

== Numerical operators

The following comparison operators are available for numeric types (`Int`, `Float`, `BigInt`), temporal types (`DateTime`) and spatial types (`Point`, `CartesianPoint`):

* `_LT_`
* `_LTE_`
* `_GTE_`
* `_GT_`

Filtering of spatial types is different to filtering of numerical types - see <<schema-filtering-spatial>>.

== String comparison

The following case-sensitive comparison operators are only available for use on `String` and `ID` types:

* `_STARTS_WITH`
* `_NOT_STARTS_WITH`
* `_ENDS_WITH`
* `_NOT_ENDS_WITH`
* `_CONTAINS`
* `_NOT_CONTAINS`

=== RegEx matching

The filter `_MATCHES` is also available for comparison of `String` and `ID` types, which accepts a RegEx string as an argument and returns any matches.

The nature of RegEx matching means that on an unprotected API, this could potentially be used to execute a ReDoS attack (https://owasp.org/www-community/attacks/Regular_expression_Denial_of_Service_-_ReDoS) against the backing Neo4j database. If this is a concern, we have added the ability to disable the inclusion of this filter by setting the environment variable `NEO4J_GRAPHQL_DISABLE_REGEX` to either `true` or `1`.

== Array comparison

The following two comparison operators are available on non-array fields, and accept an array argument:

* `_IN_`
* `_NOT_IN`

Conversely, the following operators are available on array fields, and accept a single argument:

* `_INCLUDES`
* `_NOT_INCLUDES`

These four operators are available for all types apart from `Boolean`.

[[schema-filtering-spatial]]
== Filtering of spatial types


