[[v3-migration]]
= 3.0.0 Migration
This document lists all breaking changes from version 2.x.y to 3.0.0 and how to update.

== How to upgrade
Simply update `@neo4j/graphql` using npm or your package manager of choice:

[source, bash, indent=0]
----
npm update @neo4j/graphql
----

== Async schema generation
Schema generation is now asynchronous. Instead of using the property `schema`, now the method `getSchema` will return the schema
as a _Promise_. This means that creating a server now requires awaiting for that method:

Instead of
[source, JavaScript, indent=0]
----
const neoSchema = new Neo4jGraphQL({ typeDefs, driver });
const server = new ApolloServer({
    schema: neoSchema.schema,
});
----

Now you'll need to do the following:

[source, JavaScript, indent=0]
----
const neoSchema = new Neo4jGraphQL({ typeDefs, driver });
neoSchema.getSchema().then((schema) => {
    const server = new ApolloServer({
        schema: schema
    });
});
----

== Relationship changes
This release contains an overhaul of our relationship validations, this will require a few changes to the schema.

=== Many to * relationships
To improve consistency and validation, **all** "many to *" relationships need to be defined as _required_ in the schema:

[source, graphql, indent=0]
----
type Movie {
    actors: [Actor!]! @relationship(type: "ACTED_IN", direction: IN)
    director: Director @relationship(type: "DIRECTED", direction: IN)
}
----

Note that any other notation, such as `[Actor]` or `[Actor!]` will **not** be valid. "One to one" relationships
such as `Director` remain unchanged.

=== Relationship cardinality
Runtime checks for relationships number of connections have been rolled in with this release, this means that some
databases with inconsistent relationships between the schema definition and the actual data may now fail in some queries.
For those cases, please ensure that the database is following your schema definition or update the schema to reflect the
actual existing relationships.

== Count query no longer supported
Queries using `count` at the root level are no longer supported. For example:
[source, graphql, indent=0]
----
Query {
    usersCount
}
----

The same operation, can now be achieved with a xref::queries#_counting_using_aggregation[count aggregation] query:

[source, graphql, indent=0]
----
Query {
    usersAggregate {
        count
    }
}
----

== Relationship filters
`where` filters for relationship queries now explicitly state `ALL`, `NONE`, `SINGLE`, and `SOME` as part of filter name.

Queries using old relationship filters, will now need to use `{relationship}_SOME`. For example:

[source, graphql, indent=0]
----
Query {
  movies(where: {
    actors: {
      name: "John"
    }
  }) {
    title
  }
}
----

Should be:

[source, graphql, indent=0]
----
Query {
  movies(where: {
    actors_SOME: {
      name: "John"
    }
  }) {
    title
  }
}
----

And, instead of `_NOT`, `_NONE` should be used.

NOTE: Old queries will still work in this release, but are marked as `@deprecated` and will not be available in the future.

== `@ignore` directive renamed to `@computed`
To better reflect its intended usage, the `@ignore` directive is now named `@computed`, behaviour is unchanged, so you just need to
rename this directive in your schema.

== Auth plugin system
NOTE: This section is still a work in progress.

=== jwks Endpoint

https://auth0.com/docs/secure/tokens/json-web-tokens/json-web-key-sets[JSON Web Key Sets] support through `jwksEndpoint` option is no longer
provided directly by `@neo4j/graphql`.

This feature is now available as a plugin `@neo4j/graphql-plugin-auth` that can be installed if needed:

[source, JavaScript, indent=0]
----
const { JWTPlugin } = require("@neo4j/graphql-plugin-auth");

const neoSchema = new Neo4jGraphQL({
     typeDefs,
     plugins: {
         auth: new JWTPlugin({
             secret: "secret",
         }),
     },
 });
----

== Types plurals changes
To improve consistency, some automatically generated plurals (e.g. `createActors`) have changed. This may cause issues if
your types use conventions such as `snake_case`.

Because of this, you may find generated queries and mutations may have different names. If you encounter this problem,
please update your clients to use the new query names or use the `plural` option in the xref::type-definitions/database-mapping.adoc#_plural[@node directive]
to force a custom plural value.

== Custom Directives
Defining and applying custom directives has changed significantly, if you are using or plan to use custom directives, make
sure to check the up-to-date documentation on xref::type-definitions/custom-directives.adoc[custom directives].

== Types changes
Some automatically generated types have changed to improve consistency.
These should not require any changes from most developers, unless types names are directly used.

If you are using auto-generated type names, please check the full list of xref::guides/v3-migration/generated-types.adoc[generated types changes].

== Neo4j support
Neo4j 4.1 is no longer supported in 3.0.0, inline with the https://neo4j.com/developer/kb/neo4j-supported-versions/[supported versions list].

== GraphQL support
`graphql@^15.0.0` is no longer supported, please upgrade to `graphql@^16.0.0` using `npm` or the package manager of your choice.
