[[ogm]]
= OGM

Most applications won't just expose a single GraphQL API. There may also be scheduled jobs, authentication and migrations keeping an application ticking over. The OGM (Object Graph Mapper) can be used to programmatically interact with your Neo4j GraphQL API, which may help with achieving these goals.

- xref::ogm/installation.adoc[Installation]
- xref::ogm/examples.adoc[Examples]
- xref::ogm/private.adoc[`@private` Directive]
- xref::ogm/selection-set.adoc[Selection Set]
- xref::ogm/type-generation.adoc[TypeScript Type Generation]
- xref::ogm/reference.adoc[API Reference]

> Before diving into the OGM, it's important to have a good understanding of the Neo4j GraphQL Library first. It's recommended to at least work through the xref::getting-started/index.adoc[Getting Started] guide.

== Excluded directives

The following directives are excluded from the OGM's schema:

- `@auth`
- `@exclude`
- `@private`
- `@readonly`
- `@writeonly`

This is because the OGM is only ever used programmatically, as opposed to an exposed API which needs these security measures.

See also: xref::ogm/private.adoc[`@private` Directive]

[[ogm-installation]]
== Installation

The OGM is very easy to install into a new or existing Node.js project. However it does have a couple of dependencies. The OGM depends on the Neo4j GraphQL Library, which will be installed when you install the OGM, so you will require the following dependencies:

- `@neo4j/graphql-ogm` is the OGM package.
- `graphql` is the package used by the Neo4j GraphQL Library to generate a schema and execute queries and mutations.
- `neo4j-driver` is the official Neo4j Driver package for JavaScript, necessary for interacting with the database.

[source, bash, indent=0]
----
npm install @neo4j/graphql-ogm graphql neo4j-driver
----

To use the OGM, it will need to be imported wherever you want to use it:

[source, javascript, indent=0]
----
const { OGM } = require("@neo4j/graphql-ogm");
----

It's recommended to check out the xref::ogm/examples.adoc[Examples] to see where you might go from here.

