[[v2-migration-miscellaneous]]
= Miscellaneous

== `skip` renamed to `offset`

In the release of Apollo Client 3.0, it became a bit more opinionated about pagination, favouring `offset` and `limit` over `skip` and `limit`. Acknowledging that the majority of our user base will be using Apollo Client 3.0, we have updated the page-based pagination arguments to align with this change.

For example, whilst fetching page 3 of pages of 10 movies would have looked like the following in version `1.x`:

[source, graphql]
----
query {
    movies(options: { skip: 20, limit: 10 }) {
        title
    }
}
----

This will now need to queried as follows:

[source, graphql]
----
query {
    movies(options: { offset: 20, limit: 10 }) {
        title
    }
}
----

== Count queries

Whilst not a necessary migration step, if you are using page-based pagination, it's important to note the addition of count queries in version 2.0.0. These will allow you to calculate the total number of pages for a particular filter, allowing you to implement much more effective pagination.

== Schema validation

In version 2.0.0, we have added greater levels of schema validation. However, upon upgrading, you might find that validation is too strict (for example if using certain generated types in your definitions). You can temporarily disable this new validation on construction:

[source, javascript]
----
const neoSchema = new Neo4jGraphQL({
    typeDefs,
    config: {
        skipValidateTypeDefs: true,
    },
})
----

If you need to do this, please report the scenario as an issue on GitHub.
