[[api-reference-neo4jgraphql]]
= `Neo4jGraphQL`

== `constructor`

Returns a `Neo4jGraphQL` instance.

Takes an `input` object as a parameter, the supported fields of which are described below.

=== Example

[source, javascript, indent=0]
----
const neoSchema = new Neo4jGraphQL({
    typeDefs,
});
----

[[api-reference-neo4jgraphql-input]]
=== Input

Accepts all of the options from https://github.com/ardatan/graphql-tools/blob/%40graphql-tools/schema%407.1.5/website/docs/generate-schema.md#makeexecutableschemaoptions[`makeExecutableSchema`], plus the additional arguments below:

|===
|Name and Type |Description

|`driver` +
 +
 Type: https://neo4j.com/docs/javascript-manual/current/[`Driver`]
|An instance of a Neo4j driver.

|`config` +
 +
 Type: `Neo4jGraphQLConfig`
|Additional Neo4j GraphQL configuration options.
|===

[[api-reference-neo4jgraphql-input-neo4jgraphqlconfig]]
==== `Neo4jGraphQLConfig`

|===
|Name and Type |Description

|`driverConfig` +
 +
 Type: xref::api-reference/neo4jgraphql.adoc#api-reference-neo4jgraphql-input-neo4jgraphqlconfig-driverconfig[`DriverConfig`]
|Additional driver configuration options.

|`enableRegex` +
 +
 Type: `boolean`
|Whether to enable RegEx filters, see xref::filtering.adoc#filtering-regex[RegEx matching] for more information.

|`jwt` +
 +
 Type: xref::api-reference/neo4jgraphql.adoc#api-reference-neo4jgraphql-input-neo4jgraphqlconfig-neo4jgraphqljwt[`Neo4jGraphQLJWT`]
|JWT options.

|`queryOptions` +
 +
 Type: xref::api-reference/neo4jgraphql.adoc#api-reference-neo4jgraphql-input-neo4jgraphqlconfig-cypherqueryoptions[`CypherQueryOptions`]
|Cypher query options, see xref::troubleshooting/index.adoc#troubleshooting-query-tuning[Query Tuning] for more information.

|`skipValidateTypeDefs` +
 +
 Type: `boolean`
|Can be used to disable strict type definition validation if you are encountering unexpected errors.
|===

[[api-reference-neo4jgraphql-input-neo4jgraphqlconfig-driverconfig]]
===== `DriverConfig`

|===
|Name and Type |Description

|`database` +
 +
 Type: `string`
|The name of the database within the DBMS to connect to.

|`bookmarks` +
 +
 Type: `string` or `Array<string>`
|One or more bookmarks to use for the connection.
|===

[[api-reference-neo4jgraphql-input-neo4jgraphqlconfig-neo4jgraphqljwt]]
===== `Neo4jGraphQLJWT`

|===
|Name and Type |Description

|`jwksEndpoint` +
 +
 Type: `string`
|The OpenID Public Key Set Endpoint used to verify JWT tokens. The JWKS used to store the verification information is typically stored at an endpoint similar to \https://YOUR_DOMAIN/.well-known/jwks.json. +
+
*Recommended*

|`secret` +
 +
 Type: `string`
|The secret used to encode JWT tokens.

|`noVerify` +
 +
 Type: `boolean`
|Disable verification of JWT signatures, only decode.

|`rolesPath` +
 +
 Type: `string`
|Dot path of location of roles within JWT token.
|===

[[api-reference-neo4jgraphql-input-neo4jgraphqlconfig-cypherqueryoptions]]
===== `CypherQueryOptions`

All options are enum types imported from `@neo4j/graphql`, for example:

[source, javascript, indent=0]
----
const { CypherRuntime } = require("@neo4j/graphql");
----

|===
|Name and Type |Description

|`runtime` +
 +
 Type: `CypherRuntime`
|Possible options: +
 +
 - `CypherRuntime.INTERPRETED` +
 - `CypherRuntime.SLOTTED` +
 - `CypherRuntime.PIPELINED`

|`planner` +
 +
 Type: `CypherPlanner`
|Possible options: +
 +
 - `CypherPlanner.COST` +
 - `CypherPlanner.IDP` +
 - `CypherPlanner.DP`

|`connectComponentsPlanner` +
 +
 Type: `CypherConnectComponentsPlanner`
|Possible options: +
 +
 - `CypherConnectComponentsPlanner.GREEDY` +
 - `CypherConnectComponentsPlanner.IDP`

|`updateStrategy` +
 +
 Type: `CypherUpdateStrategy`
|Possible options: +
 +
 - `CypherUpdateStrategy.DEFAULT` +
 - `CypherUpdateStrategy.EAGER`

|`expressionEngine` +
 +
 Type: `CypherExpressionEngine`
|Possible options: +
 +
 - `CypherExpressionEngine.DEFAULT` +
 - `CypherExpressionEngine.INTERPRETED` +
 - `CypherExpressionEngine.COMPILED`

|`operatorEngine` +
 +
 Type: `CypherOperatorEngine`
|Possible options: +
 +
 - `CypherOperatorEngine.DEFAULT` +
 - `CypherOperatorEngine.INTERPRETED` +
 - `CypherOperatorEngine.COMPILED`

|`interpretedPipesFallback` +
 +
 Type: `CypherInterpretedPipesFallback`
|Possible options: +
 +
 - `CypherInterpretedPipesFallback.DEFAULT` +
 - `CypherInterpretedPipesFallback.DISABLED` +
 - `CypherInterpretedPipesFallback.WHITELISTED_PLANS_ONLY` +
 - `CypherInterpretedPipesFallback.ALL`

|`replan` +
 +
 Type: `CypherReplanning`
|Possible options: +
 +
 - `CypherReplanning.DEFAULT` +
 - `CypherReplanning.FORCE` +
 - `CypherReplanning.SKIP`
|===

[[api-reference-checkneo4jcompat]]
== `checkNeo4jCompat`

Asynchronous function to check the compatibility of the specified DBMS, that either resolves to `void` in a successful scenario, or throws an error if the database is not compatible with the Neo4j GraphQL Library.

Takes an `input` object as a parameter, the supported fields of which are described below.

=== Example

Given any valid type definitions saved to the variable `typeDefs` and a valid driver instance saved to the variable `driver`, the following will confirm database compatibility:

[source, javascript, indent=0]
----
const neoSchema = new Neo4jGraphQL({ typeDefs, driver });
await neoSchema.checkNeo4jCompat();
----

[[api-reference-checkneo4jcompat-input]]
=== Input

Accepts the arguments below:

|===
|Name and Type |Description

|`driver` +
 +
 Type: https://neo4j.com/docs/javascript-manual/current/[`Driver`]
|An instance of a Neo4j driver.

|`driverConfig` +
 +
 Type: xref::api-reference/neo4jgraphql.adoc#api-reference-checkneo4jcompat-input-driverconfig[`DriverConfig`]
|Additional driver configuration options.
|===

[[api-reference-checkneo4jcompat-input-driverconfig]]
==== `DriverConfig`

|===
|Name and Type |Description

|`database` +
 +
 Type: `string`
|The name of the database within the DBMS to connect to.

|`bookmarks` +
 +
 Type: `string` or `Array<string>`
|One or more bookmarks to use for the connection.
|===

[[api-reference-assertconstraints]]
== `assertIndexesAndConstraints`

Asynchronous function to assert the existence of database constraints, that either resolves to `void` in a successful scenario, or throws an error if the necessary consraints do not exist following its execution.

Takes an `input` object as a parameter, the supported fields of which are described below.

=== Example

Given the following type definitions saved to the variable `typeDefs` and a valid driver instance saved to the variable `driver`:

[source, graphql, indent=0]
----
type Book {
    isbn: String! @unique
}
----

And the construction of a `Neo4jGraphQL`, using:

[source, javascript, indent=0]
----
const neoSchema = new Neo4jGraphQL({ typeDefs, driver });
----

The following will check whether a unique node property constraint exists for label "Book" and property "isbn", and throw an error if it does not:

[source, javascript, indent=0]
----
await neoSchema.assertIndexesAndConstraints();
----

The next example will create the constraint if it does not exist:

[source, javascript, indent=0]
----
await neoSchema.assertIndexesAndConstraints({ options: { create: true } });
----

[[api-reference-assertconstraints-input]]
=== Input

Accepts the arguments below:

|===
|Name and Type |Description

|`driver` +
 +
 Type: https://neo4j.com/docs/javascript-manual/current/[`Driver`]
|An instance of a Neo4j driver.

|`driverConfig` +
 +
 Type: xref::api-reference/neo4jgraphql.adoc#api-reference-assertconstraints-input-driverconfig[`DriverConfig`]
|Additional driver configuration options.

|`options` +
 +
 Type: xref::api-reference/neo4jgraphql.adoc#api-reference-assertconstraints-input-assertconstraintsoptions[`AssertConstraintsOptions`]
|Options for the execution of `assertIndexesAndConstraints`.
|===

[[api-reference-assertconstraints-input-driverconfig]]
==== `DriverConfig`

|===
|Name and Type |Description

|`database` +
 +
 Type: `string`
|The name of the database within the DBMS to connect to.

|`bookmarks` +
 +
 Type: `string` or `Array<string>`
|One or more bookmarks to use for the connection.
|===

[[api-reference-assertconstraints-input-assertconstraintsoptions]]
==== `AssertConstraintsOptions`

|===
|Name and Type |Description

|`create` +
 +
 Type: `boolean`
|Whether or not to create constraints if they do not yet exist. Disabled by default.
|===
