[[auth-authentication]]
= Authentication

Neo4j GraphQL will expect there to be an `authorization` header in the request object, which means you can authenticate users however you like. You could; Have a custom sign-in mutation, integrate with Auth0, or roll your own SSO server. The point here is that it’s just a JWT, in the library, we will decode it to make sure it’s valid - but it’s down to you to issue tokens.

== OGM

Here we will use the <<ogm>> to set up a hypothetical sign-in flow;


[source, javascript]
----
const { Neo4jGraphQL } = require("@neo4j-graphql");
const { createJWT, comparePassword } = require("./utils"); // example
const { ApolloServer } = require("apollo-server");
const { OGM } = require("@neo4j-graphql-ogm");

const typeDefs = `
    type User {
        id: ID @id
        email: String!
        password: String!
    }

    type Mutation {
        signIn(email: String!, password: String!): String ## token
    }
`;

const driver = neo4j.driver("bolt://localhost:7687", neo4j.auth.basic("admin", "password"));

const ogm = new OGM({
    typeDefs,
    driver,
});

const User = ogm.model("User");

const resolvers = {
    Mutation: {
        async signIn(root, { email, password }) {
            const [existing] = await User.find({
                where: {
                    email,
                },
            });

            if (!existing) {
                throw new Error("not found");
            }

            const equal = await comparePassword(password, existing.password);
            if (!equal) {
                throw new Error("bad password");
            }

            return createJWT({
                sub: user.id,
            });
        },
    },
};

const neoSchema = new Neo4jGraphQL({
    typeDefs,
    resolvers,
    driver,
    config: {
        jwt: {
            secret
        }
    }
});

const server = new ApolloServer({
    schema: neoSchema.schema,
    context: ({ req }) => ({ req }),
});

server.listen(4000).then(() => console.log("online"));
----

== `isAuthenticated`
This is the most basic of auth. Used to ensure that there is a valid decoded JWT in the request. The most basic of applications could look something like this;

[source, graphql]
----
type Todo {
    id: ID
    title: String
}

extend type Todo @auth(rules: [{ isAuthenticated: true }])
----

== `allowUnauthenticated`
In some cases, you may want to allow unauthenticated requests while also having auth-based rules. You can use the `allowUnauthenticated` parameter to avoid throwing an exception if no auth is present in the context.

In the example below, only the publisher can see his blog posts even if it is not published yet. Once the blog post is published, anyone can see it.

WARNING: In case of unauthenticated requests, auth parameters will be replaced by `null` in the cypher query. In this case, `publisher: "$jwt.sub"` will become `publisher: null`; This can lead to unwanted results if the field used for querying is nullable in Neo4J.

[source, graphql]
----
type BlogPost {
    id: ID!
    publisher: User!
    published: Boolean!
}

extend type BlogPost {
    password: String! @auth(rules: [
        { operations: [READ], where: { OR: [
            { publisher: "$jwt.sub" },
            { published: true },
        ] }, allowUnauthenticated: true }
    ])
}
----