name: Reopened bug reports

on:
  issues:
    types: [reopened]

jobs:
  add-reopened-bugs-to-triage:
    if: contains(github.event.issue.labels.*.name, 'bug report')

    runs-on: ubuntu-latest

    steps:
      - uses: alex-page/github-project-automation-plus@be108970955040d35dd6d053c3aff3faaf678026
        with:
          project: Bug Triage
          column: Bug reports
          repo-token: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
          action: update
      - name: add labels
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          add-labels: "reopened"
          repo-token: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
