name: Reopened bug reports

on:
  issues:
    types: [reopened]

jobs:
  add-reopened-bugs-to-triage:
    if: contains(github.event.issue.labels.*.name, 'bug report')

    runs-on: ubuntu-latest

    steps:
      - uses: alex-page/github-project-automation-plus@1f8873e97e3c8f58161a323b7c568c1f623a1c4d # tag=v0.8.2
        with:
          project: Bug Triage
          column: Bug reports
          repo-token: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
          action: update
      - name: add labels
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90 # renovate: tag=v1.0.4
        with:
          add-labels: "reopened"
          repo-token: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
