name: changesets

on:
  push:
    branches:
      - dev
      - lts
      - "*.*.*"
      - "*.x"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest

    environment:
      name: npm

    outputs:
      published: ${{ steps.changesets.outputs.published }}
      published-packages: ${{ steps.changesets.outputs.publishedPackages }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: yarn

      - name: Configure git
        run: |
          git config --global user.name 'Neo4j Team GraphQL'
          git config --global user.email 'team-graphql@neotechnology.com'

      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            @neo4j:registry https://registry.npmjs.org
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create release PR or release
        id: changesets
        uses: changesets/action@746c25e23caa47dceb6a48ee85b4cbc5a9f5f293 # v1.5.0
        with:
          title: changesets for branch `${{ github.ref_name }}`
          version: yarn changeset-version
          # Don't use a custom tag if either latest build or prerelease (error under changesets)
          publish: yarn ${{ (github.ref_name == 'dev' || hashFiles('.changeset/pre.json') != '') && 'release-dev' || 'release-tagged' }}
          setupGitUser: false
        env:
          GITHUB_TOKEN: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
          BRANCH: ${{ github.ref_name }}

  slack-notify:
    needs:
      - release

    if: ${{ needs.release.outputs.published == 'true' }}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ fromJson(needs.release.outputs.published-packages) }}

    steps:
      - name: Send Slack announcement of release
        if: matrix.package.name == '@neo4j/graphql'
        uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d # v2.0.0
        with:
          payload: |
            version: ${{ matrix.package.version }}
          webhook: ${{ secrets.SLACK_RELEASE_ANNOUNCEMENT_WEBHOOK_URL }}
          webhook-type: webhook-trigger
