name: "CLA Assistant"

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

# explicitly configure permissions, in case your GITHUB_TOKEN workflow permissions are set to read-only in repository settings
permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@5bfe123a0731f017d9c29550976bf724fe0870f5 # renovate: tag=v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # the below token should have repo scope and must be manually added by you in the repository's secret
          # This token is required only if you have configured to store the signatures in a remote repository/organization
          PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_ASSISTANT_PERSONAL_ACCESS_TOKEN }}
        with:
          path-to-signatures: 'signatures.json'
          path-to-document: 'https://gist.github.com/neo4j-cla-assistant/3225cd90cce7c8498b716e7077a43734' # e.g. a CLA or a DCO document
          # branch should not be protected
          branch: 'main'
          allowlist: renovate[bot],neo4j-team-graphql
          remote-organization-name: neo4j
          remote-repository-name: cla-assistant
          lock-pullrequest-aftermerge: false # if you don't want this bot to automatically lock the pull request after merging (default - true)
