name: "Documentation Teardown"

on:
  pull_request_target:
    branches:
      - dev
      - master
    paths:
      - docs/antora.yml
      - docs/package.json
      - "docs/modules/ROOT/**"
    types:
      - closed

jobs:
  teardown-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Teardown documentation
        run: |
          npm install -g surge
          surge teardown neo4j-graphql-docs-${{ github.event.pull_request.number }}.surge.sh --token ${{ secrets.SURGE_TOKEN }}
      - name: Comment on PR
        uses: marocchino/sticky-pull-request-comment@97bddef64db61b9d80edc69593cc4e4c415c3362 # tag=v2.2.1
        with:
          message: |
            Thanks for the documentation updates.

            The preview documentation has now been torn down - reopening this PR will republish it.
          GITHUB_TOKEN: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
