name: "@neo4j/graphql Documentation"

on:
  pull_request:
    branches:
      - master
    paths:
      - 'docs/**'
    types: 
      - opened
      - closed
      - reopened 
      - synchronize   
      
jobs:
  publish-docs:
    if: github.event.action != 'closed'
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Install, build and publish documentation
        run: |
          npm install -g surge
          npm install
          npm run build
          surge ./build/site/ neo4j-graphql-docs-${{ github.event.pull_request.number }}.surge.sh --token ${{ secrets.SURGE_TOKEN }}
        working-directory: docs/
      - name: Comment on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            Looks like you've updated the documentation!

            Check out your changes at https://neo4j-graphql-docs-${{ github.event.pull_request.number }}.surge.sh
          GITHUB_TOKEN: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
        
  teardown-docs:
    if: github.event.action == 'closed'
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Teardown documentation
        run: |
          npm install -g surge
          surge teardown neo4j-graphql-docs-${{ github.event.pull_request.number }}.surge.sh --token ${{ secrets.SURGE_TOKEN }}
      - name: Comment on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            Thanks for the documentation updates.

            The preview documentation has now been torn down - reopening this PR will republish it.
          GITHUB_TOKEN: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
