name: "Pull Request Labeler"

on:
  pull_request_target:
    branches:
      - dev
      - lts

jobs:
  label:
    if: ${{ !startsWith(github.event.pull_request.head.ref, 'renovate/') }}

    runs-on: ubuntu-latest

    steps:
      - uses: srvaroa/labeler@0a20eccb8c94a1ee0bed5f16859aece1c45c3e55 # v1.13.0
        env:
          GITHUB_TOKEN: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
