name: "Lint Markdown"

on:
  pull_request:
    branches:
      - dev
      - lts
    paths:
      - "**/*.md"

jobs:
  markdownlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: lts/*
          package-manager-cache: false
      - name: Install markdownlint
        run: npm install -g markdownlint-cli
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: filter
        with:
          list-files: shell
          filters: |
            markdown:
              - added|modified: '*.md'
      - uses: xt0rted/markdownlint-problem-matcher@1a5fabfb577370cfdf5af944d418e4be3ea06f27 # v3.0.0
      - name: Run markdownlint
        run: markdownlint --config ./.markdownlint.json ${{ steps.filter.outputs.markdown_files }}
