name: "Lint GitHub Actions"

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
    paths:
      - ".github/workflows/**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: reviewdog/action-actionlint@ab7138020abfe6cd20b742c82e5b7a9749fb5884 # v1.75.0
        with:
          reporter: github-check
          fail_on_error: true
