name: "Lint Markdown"

on:
  pull_request:
    branches:
      - dev
      - lts
    paths:
      - "**/*.md"

jobs:
  markdownlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: lts/*
          package-manager-cache: false
      - name: Install markdownlint
        run: npm install -g markdownlint-cli
      - uses: dorny/paths-filter@d1c1ffe0248fe513906c8e24db8ea791d46f8590 # v3.0.3
        id: filter
        with:
          list-files: shell
          filters: |
            markdown:
              - added|modified: '*.md'
      - uses: xt0rted/markdownlint-problem-matcher@1a5fabfb577370cfdf5af944d418e4be3ea06f27 # v3.0.0
      - name: Run markdownlint
        run: markdownlint --config ./.markdownlint.json ${{ steps.filter.outputs.markdown_files }}
