name: "Lint Markdown"

on:
  pull_request:
    branches:
      - dev
      - lts
    paths:
      - "**/*.md"

jobs:
  markdownlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
        with:
          node-version: lts/*
          package-manager-cache: false
      - name: Install markdownlint
        run: npm install -g markdownlint-cli
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          list-files: shell
          filters: |
            markdown:
              - added|modified: '*.md'
      - uses: xt0rted/markdownlint-problem-matcher@1a5fabfb577370cfdf5af944d418e4be3ea06f27 # v3.0.0
      - name: Run markdownlint
        run: markdownlint --config ./.markdownlint.json ${{ steps.filter.outputs.markdown_files }}
