name: "Lint GitHub Actions"

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
    paths:
      - ".github/workflows/**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: reviewdog/action-actionlint@0d952c597ef8459f634d7145b0b044a9699e5e43 # v1.71.0
        with:
          reporter: github-check
          fail_on_error: true
