name: "Lint GitHub Actions"

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
    paths:
      - ".github/workflows/**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - uses: reviewdog/action-actionlint@f00ad0691526c10be4021a91b2510f0a769b14d0 # v1.68.0
        with:
          reporter: github-check
          fail_on_error: true
