# This is a basic workflow to help you get started with Actions

name: "@neo4j/graphql CI"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn --immutable
      - run: yarn build
      - name: Run @neo4j/graphql unit tests
        run: yarn --cwd packages/graphql run test:unit
      - name: Run @neo4j/graphql TCK tests
        run: yarn --cwd packages/graphql run test:tck
      - name: Run @neo4j/graphql package tests
        run: yarn --cwd packages/graphql run test:package-tests
      - name: Run @neo4j/graphql-ogm unit tests
        run: yarn --cwd packages/ogm run test:unit
