name: "Markdown Lint"

on:
  pull_request:
    branches:
      - dev
    paths:
      - "**/*.md"

jobs:
  markdownlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Install markdownlint
        run: npm install -g markdownlint-cli
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          filters: |
            markdown:
              - added|modified: '*.md'
      - name: Install markdownlint
        run: markdownlint --config ./.markdownlint.json ${{ steps.filter.outputs.markdown_files }}
