name: "Post Apollo Federation Subgraph Compatibility results"

on:
  workflow_run:
    workflows: ["Apollo Federation Subgraph Compatibility"]
    types:
      - completed

jobs:
  post-results:
    if: github.event.workflow_run.conclusion == 'success'

    runs-on: ubuntu-latest

    steps:
      - name: "Download Apollo Federation Subgraph Compatibility results"
        uses: actions/github-script@v6.4.1
        with:
          script: |
            var artifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{ github.event.workflow_run.id }},
            });
            var matchArtifacts = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "compatibility-results" || artifact.name == "prnumber"
            });

            var fs = require('fs');

            for (var matchArtifact of matchArtifacts) {
              var download = await github.rest.actions.downloadArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: matchArtifact.id,
                archive_format: 'zip',
              });

              var workspace = '${{ github.workspace }}';
              
              fs.writeFileSync(`${workspace}/${matchArtifact.name}.zip', Buffer.from(download.data));
            }
      - run: unzip compatibility-results.zip
      - run: unzip prnumber.zip
      - id: get-pr-number
        run: |
          number=$(<prnumber)
          case "$number" in ''|*[!0-9]*) echo "Provided PR number is not an integer"; exit 1 ;; esac
          echo "pr-number=$number" >> "$GITHUB_OUTPUT"
      - name: Comment on PR
        uses: marocchino/sticky-pull-request-comment@3d60a5b2dae89d44e0c6ddc69dd7536aec2071cd # v2.5.0
        with:
          number: ${{ steps.get-pr-number.outputs.pr-number }}
          header: federation
          path: ./results.md
          GITHUB_TOKEN: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
