name: Pull request labeled

on:
  pull_request_target:
    types: [labeled]

jobs:
  add_confirmed_comment:
    if: ${{ github.event.label.name == 'rfc' }}

    runs-on: ubuntu-latest

    steps:
      - uses: alex-page/github-project-automation-plus@1f8873e97e3c8f58161a323b7c568c1f623a1c4d # tag=v0.8.2
        with:
          project: RFCs
          column: RFCs
          repo-token: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
          action: add
