# This is a basic workflow to help you get started with Actions

name: "@neo4j/graphql CI"

# Controls when the workflow will run
on:
  pull_request:
    branches: [ master ]

jobs:
  cla:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with: 
          repository: neo-technology/whitelist-check
          ssh-key: ${{ secrets.NEO_TECHNOLOGY_BUILD_AGENT_SSH_KEY }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - run: ./bin/examine-pull-request neo4j graphql "${{ secrets.NEO_TECHNOLOGY_BUILD_AGENT_TOKEN }}" ${{ env.GITHUB_HEAD_REF }} cla-database.csv
