name: "Pull Request Opened"

on:
  pull_request_target:
    types:
      - opened
    paths-ignore:
      - docs/rfcs/.*

jobs:
  add-new-pull-requests-to-triage:
    if: "!startsWith(github.event.pull_request.head.ref, 'renovate/')"

    runs-on: ubuntu-latest

    steps:
      - uses: alex-page/github-project-automation-plus@be108970955040d35dd6d053c3aff3faaf678026
        with:
          project: PR Triage
          column: Pull requests
          repo-token: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
          action: add
