name: "Pull Request Opened"

on:
  pull_request_target:
    types:
      - opened
    paths-ignore:
      - docs/rfcs/.*

jobs:
  add-new-pull-requests-to-triage:
    if: "!startsWith(github.event.pull_request.head.ref, 'renovate/')"

    runs-on: ubuntu-latest

    steps:
      - uses: alex-page/github-project-automation-plus@1f8873e97e3c8f58161a323b7c568c1f623a1c4d # tag=v0.8.2
        with:
          project: PR Triage
          column: Pull requests
          repo-token: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
          action: add
