# NOTE: This filename must be called release.yml. If changed, update the Trusted Publisher settings in npm

name: Release

on:
  push:
    branches:
      - dev
      - lts
      - "*.x"

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  id-token: write # Required for OIDC

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest

    environment:
      name: npm

    outputs:
      published: ${{ steps.changesets.outputs.published }}
      published-packages: ${{ steps.changesets.outputs.publishedPackages }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org
          package-manager-cache: false

      - name: Update npm # Need at least 11.5.1 for OIDC publishing
        run: npm install -g npm@latest

      - name: Install Dependencies
        run: yarn

      - name: Configure git
        run: |
          git config --global user.name 'Neo4j Team GraphQL'
          git config --global user.email 'team-graphql@neotechnology.com'

      - name: Create release PR or release
        id: changesets
        uses: changesets/action@c48e67d110a68bc90ccf1098e9646092baacaa87 # v1.6.0
        with:
          title: changesets for branch `${{ github.ref_name }}`
          version: yarn changeset-version
          # Don't use a custom tag if either latest build or prerelease (error under changesets)
          publish: yarn ${{ ((github.ref_name == 'dev' || hashFiles('.changeset/pre.json') != '') && 'release-dev') || (github.ref_name == 'lts' && 'release-lts') || 'release-previous' }}
          setupGitUser: false
        env:
          GITHUB_TOKEN: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
          BRANCH: ${{ github.ref_name }}

  slack-notify:
    needs:
      - release
    if: ${{ needs.release.outputs.published == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ fromJson(needs.release.outputs.published-packages) }}

    steps:
      - name: Send Slack announcement of release
        if: matrix.package.name == '@neo4j/graphql'
        uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
        with:
          payload: |
            version: ${{ matrix.package.version }}
          webhook: ${{ secrets.SLACK_RELEASE_ANNOUNCEMENT_WEBHOOK_URL }}
          webhook-type: webhook-trigger
