# NOTE: This filename must be called release.yml. If changed, update the Trusted Publisher settings in npm

name: Release

on:
  push:
    branches:
      - dev
      - lts
      - "*.x"

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  id-token: write # Required for OIDC

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest

    environment:
      name: npm

    outputs:
      published: ${{ steps.changesets.outputs.published }}
      published-packages: ${{ steps.changesets.outputs.publishedPackages }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org
          package-manager-cache: false

      - name: Update npm # Need at least 11.5.1 for OIDC publishing. Pinned to v11: npm 12 changed `npm info --json` output and "already published" errors, breaking `changeset publish` (https://github.com/changesets/changesets/issues/2099)
        run: npm install -g npm@11.19.1

      - name: Install Dependencies
        run: yarn

      - name: Configure git
        run: |
          git config --global user.name 'Neo4j Team GraphQL'
          git config --global user.email 'team-graphql@neotechnology.com'

      - name: Create release PR or release
        id: changesets
        uses: changesets/action@a45c4d594aa4e2c509dc14a9f2b3b67ba3780d0d # v1.9.0
        with:
          title: changesets for branch `${{ github.ref_name }}`
          version: yarn changeset-version
          # Don't use a custom tag if either latest build or prerelease (error under changesets)
          publish: yarn ${{ ((github.ref_name == 'dev' || hashFiles('.changeset/pre.json') != '') && 'release-dev') || (github.ref_name == 'lts' && 'release-lts') || 'release-previous' }}
          setupGitUser: false
        env:
          GITHUB_TOKEN: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
          BRANCH: ${{ github.ref_name }}

  slack-notify:
    needs:
      - release
    if: ${{ needs.release.outputs.published == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ fromJson(needs.release.outputs.published-packages) }}

    steps:
      - name: Send Slack announcement of release
        if: matrix.package.name == '@neo4j/graphql'
        uses: slackapi/slack-github-action@0d95c9a7becc1e6e297d76df9bc735c44f4cbcbc # v3.0.5
        with:
          payload: |
            version: ${{ matrix.package.version }}
          webhook: ${{ secrets.SLACK_RELEASE_ANNOUNCEMENT_WEBHOOK_URL }}
          webhook-type: webhook-trigger
