name: "Release (Toolbox)"

on:
  push:
    branches:
      - release/toolbox/*
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  cache-dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - name: Install dependencies
        run: yarn --immutable

  unit-tests:
    needs:
      - cache-dependencies

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Run packages/graphql-toolbox unit tests
        run: yarn run test:unit
        working-directory: packages/graphql-toolbox

  toolbox-e2e-tests:
    needs:
      - cache-dependencies

    uses: ./.github/workflows/reusable-toolbox-tests.yml

  bump-version:
    needs:
      - unit-tests
      - toolbox-e2e-tests

    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.get-version.outputs.version }}

    steps:
      - uses: actions/checkout@v3
        with:
          # Fetch all history so yarn version works
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Extract version from branch name
        id: get-version
        run: |
          version=$(echo ${{ github.ref }} | cut -d/ -f5)
          echo "::set-output name=version::$version"
      - name: Bump @neo4j/graphql-toolbox version
        run: yarn version "${{ steps.get-version.outputs.version }}"
        working-directory: packages/graphql-toolbox
      - name: Commit and push new version numbers
        run: |
          git config --global user.name 'Neo4j Team GraphQL'
          git config --global user.email 'team-graphql@neotechnology.com'
          git commit -am "Bump @neo4j/graphql-toolbox version to ${{ steps.get-version.outputs.version }}"
          git push

  deploy:
    needs:
      - bump-version

    runs-on: ubuntu-latest
    
    environment:
      name: aws
    
    steps:
      - uses: actions/checkout@v3
        with:
          ref: release/toolbox/${{ needs.bump-version.outputs.version }}
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Build graphql-toolbox
        run: yarn build
        working-directory: packages/graphql-toolbox
      - uses: jakejarvis/s3-sync-action@be0c4ab89158cac4278689ebedd8407dd5f35a83 # renovate: tag=v0.5.1
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-west-2"
          SOURCE_DIR: "packages/graphql-toolbox/dist" # optional: defaults to entire repository

  merge-tag-push:
    needs:
      - bump-version
      - deploy

    runs-on: ubuntu-latest

    environment:
      name: github

    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0
          token: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
      - name: git config
        run: |
          git config --global user.name 'Neo4j Team GraphQL'
          git config --global user.email 'team-graphql@neotechnology.com'
      - name: git merge
        run: git merge --no-ff origin/release/toolbox/${{ needs.bump-version.outputs.version }} --strategy-option theirs
      - name: git tag
        run: |
          git tag -a @neo4j/graphql-toolbox@${{ needs.bump-version.outputs.version }} -m "@neo4j/graphql-toolbox@${{ needs.bump-version.outputs.version }}"
      - name: git push
        run: git push --follow-tags
      - uses: actions/checkout@v3
        with:
          ref: dev
          fetch-depth: 0
          token: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
      - name: git merge
        run: git merge --no-ff origin/release/toolbox/${{ needs.bump-version.outputs.version }} --strategy-option theirs
      - name: git push
        run: git push

  delete-release-branch:
    needs:
      - bump-version
      - merge-tag-push

    runs-on: ubuntu-latest

    environment:
      name: github

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
      - name: Delete release branch
        run: |
          git config --global user.name 'Neo4j Team GraphQL'
          git config --global user.email 'team-graphql@neotechnology.com'
          git push origin --delete release/toolbox/${{ needs.bump-version.outputs.version }}

  changelog:
    needs:
      - bump-version
      - merge-tag-push

    strategy:
      matrix:
        package:
          - graphql-toolbox

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Extract prerelease from version
        id: get-prerelease
        run: |
          prerelease=$(echo ${{ needs.bump-version.outputs.version }} | cut -d@ -f3 | cut -d- -f2)
          echo "::set-output name=prerelease::$prerelease"
      - name: Build Changelog
        id: github-release
        uses: mikepenz/release-changelog-builder-action@c9066537c0c7bc5c7b0ec7722cefc02524c7c005 # renovate: tag=v3.1.0
        with:
          configuration: "config/release-changelog-builder-action/configuration-toolbox.json"
          toTag: "@neo4j/${{ matrix.package }}@${{ needs.bump-version.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5 # renovate: tag=v0.1.14
        with:
          body: ${{ steps.github-release.outputs.changelog }}
          name: "@neo4j/${{ matrix.package }}@${{ needs.bump-version.outputs.version }}"
          tag_name: "@neo4j/${{ matrix.package }}@${{ needs.bump-version.outputs.version }}"
          prerelease: |
            ${{ startsWith(steps.get-prerelease.outputs.prerelease, 'alpha') }} ||
            ${{ startsWith(steps.get-prerelease.outputs.prerelease, 'beta') }} ||
            ${{ startsWith(steps.get-prerelease.outputs.prerelease, 'rc') }}
