name: "Release (Subscriptions AMQP Plugin)"

on:
  push:
    branches:
      - release/plugin-subscriptions-amqp/*
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  cache-dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - name: Install dependencies
        run: yarn --immutable

  e2e-tests-plugins:
    needs:
      - cache-dependencies

    uses: ./.github/workflows/reusable-subscriptions-plugin-amqp-e2e-test.yml

  bump-version:
    needs:
      - e2e-tests-plugins

    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.get-version.outputs.version }}

    steps:
      - uses: actions/checkout@v3
        with:
          # Fetch all history so yarn version works
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Extract version from branch name
        id: get-version
        run: |
          version=$(echo ${{ github.ref }} | cut -d/ -f5)
          echo "::set-output name=version::$version"
      - name: Bump @neo4j/graphql-plugin-subscriptions-amqp version
        run: yarn version "${{ steps.get-version.outputs.version }}"
        working-directory: packages/plugins/graphql-plugin-subscriptions-amqp
      - name: Commit and push new version numbers
        run: |
          git config --global user.name 'Neo4j Team GraphQL'
          git config --global user.email 'team-graphql@neotechnology.com'
          git commit -am "Bump @neo4j/graphql-plugin-subscriptions-amqp version to ${{ steps.get-version.outputs.version }}"
          git push

  pack:
    needs:
      - bump-version

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: release/plugin-subscriptions-amqp/${{ needs.bump-version.outputs.version }}
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Build plugin
        run: yarn build
        working-directory: packages/plugins/graphql-plugin-subscriptions-amqp
      - name: Pack plugin
        run: npm pack
        working-directory: packages/plugins/graphql-plugin-subscriptions-amqp
      - name: Archive release tarball
        uses: actions/upload-artifact@v3
        with:
          name: release-tarballs
          path: packages/plugins/graphql-plugin-subscriptions-amqp/neo4j-graphql-plugin-subscriptions-amqp-*.tgz

  npm-publish:
    needs:
      - bump-version
      - pack

    runs-on: ubuntu-latest

    environment:
      name: npm

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: release-tarballs
      - name: npm publish
        run: |
          prerelease=$(echo ${{ needs.bump-version.outputs.version }} | cut -d- -f2)

          if [[ "$prerelease" =~ ^(alpha|beta|rc)\..* ]]; then
            tag="next"
          else
            tag="latest"
          fi

          npm config set @neo4j:registry https://registry.npmjs.org
          npm config set //registry.npmjs.org/:_authToken "$NPM_TOKEN"

          for tarball in *.tgz
          do
            npm publish "$tarball" --tag=$tag --access=public
          done
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  merge-tag-push:
    needs:
      - bump-version
      - npm-publish

    runs-on: ubuntu-latest

    environment:
      name: github

    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0
          token: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
      - name: git config
        run: |
          git config --global user.name 'Neo4j Team GraphQL'
          git config --global user.email 'team-graphql@neotechnology.com'
      - name: git merge
        run: git merge --no-ff origin/release/plugin-subscriptions-amqp/${{ needs.bump-version.outputs.version }} --strategy-option theirs
      - name: git tag
        run: |
          git tag -a @neo4j/graphql-plugin-subscriptions-amqp@${{ needs.bump-version.outputs.version }} -m "@neo4j/graphql-plugin-subscriptions-amqp@${{ needs.bump-version.outputs.version }}"
      - name: git push
        run: git push --follow-tags
      - uses: actions/checkout@v3
        with:
          ref: dev
          fetch-depth: 0
          token: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
      - name: git merge
        run: git merge --no-ff origin/release/plugin-subscriptions-amqp/${{ needs.bump-version.outputs.version }} --strategy-option theirs
      - name: git push
        run: git push

  delete-release-branch:
    needs:
      - bump-version
      - merge-tag-push

    runs-on: ubuntu-latest

    environment:
      name: github

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
      - name: Delete release branch
        run: |
          git config --global user.name 'Neo4j Team GraphQL'
          git config --global user.email 'team-graphql@neotechnology.com'
          git push origin --delete release/plugin-subscriptions-amqp/${{ needs.bump-version.outputs.version }}

  changelog:
    needs:
      - bump-version
      - merge-tag-push

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Extract prerelease from version
        id: get-prerelease
        run: |
          prerelease=$(echo ${{ needs.bump-version.outputs.version }} | cut -d@ -f3 | cut -d- -f2)
          echo "::set-output name=prerelease::$prerelease"
      - name: Build Changelog
        id: github-release
        uses: mikepenz/release-changelog-builder-action@401210947fa212918c4d4f2fa2c82e0ec94a0a79
        with:
          configuration: "config/release-changelog-builder-action/configuration-plugin-subscriptions-amqp.json"
          toTag: "@neo4j/graphql-plugin-subscriptions-amqp@${{ needs.bump-version.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@cd28b0f5ee8571b76cfdaa62a30d51d752317477
        with:
          body: ${{ steps.github-release.outputs.changelog }}
          name: "@neo4j/graphql-plugin-subscriptions-amqp@${{ needs.bump-version.outputs.version }}"
          tag_name: "@neo4j/graphql-plugin-subscriptions-amqp@${{ needs.bump-version.outputs.version }}"
          prerelease: |
            ${{ startsWith(steps.get-prerelease.outputs.prerelease, 'alpha') }} ||
            ${{ startsWith(steps.get-prerelease.outputs.prerelease, 'beta') }} ||
            ${{ startsWith(steps.get-prerelease.outputs.prerelease, 'rc') }}
