name: "@neo4j/graphql-amqp-subscriptions-engine E2E tests"

on:
  workflow_call:

jobs:
  e2e-tests:
    strategy:
      fail-fast: false
      matrix:
        graphql-version:
          - "^15.0.0"
          - "^16.0.0"
        neo4j-version:
          #   - 4.4-community
          - 4.4-enterprise
          #   - 5-community
          - 5-enterprise
    services:
      neo4j:
        image: neo4j:${{ matrix.neo4j-version }}
        env:
          NEO4J_AUTH: neo4j/mypassword
          NEO4J_PLUGINS: '["apoc"]'
          NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
        ports:
          - 7687:7687
      rabbitmq:
        image: rabbitmq@sha256:d3356b10fd1afd503b58f53d267e9561338501d5ba4e9cf2f62b4250e55fece4
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672:5672

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: lts/*
          cache: yarn
          package-manager-cache: false
      - name: Install dependencies
        run: yarn --immutable
      - name: Overwrite GraphQL version
        run: yarn up --exact graphql@${{ matrix.graphql-version }}
      - name: Run packages/graphql-amqp-subscriptions-engine e2e tests
        run: yarn run test:e2e --coverage
        working-directory: packages/graphql-amqp-subscriptions-engine
        env:
          NEO_USER: neo4j
          NEO_PASSWORD: mypassword
          NEO_URL: bolt://localhost:7687
          RABBITMQ_HOST: localhost
          RABBITMQ_USER: guest
          RABBITMQ_PASSWORD: guest
      - name: Archive coverage report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: e2e-coverage-graphql-amqp-subscriptions-engine-${{ matrix.graphql-version }}-${{ matrix.neo4j-version }}
          path: packages/graphql-amqp-subscriptions-engine/coverage/

  merge-e2e-tests-results:
    runs-on: ubuntu-latest
    needs: e2e-tests
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: e2e-coverage-graphql-amqp-subscriptions-engine
          pattern: e2e-coverage-graphql-amqp-subscriptions-engine-*
