name: "Package tests"

on:
  workflow_call:

jobs:
  package-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 20 # Should match package.json minimum node engine
          cache: yarn
          package-manager-cache: false
      - name: Install dependencies
        run: yarn
      - name: Build graphql
        run: yarn build
        working-directory: packages/graphql
      - name: Run @neo4j/graphql package tests
        run: yarn --cwd packages/graphql run test:package-tests
