name: "Unit tests"

on:
  workflow_call:
    inputs:
      disable-coverage-archival:
        description: "Whether or not to archive the test coverage"
        required: false
        default: false
        type: boolean

jobs:
  unit-tests:
    strategy:
      matrix:
        package:
          - graphql
          - ogm
          - introspector
          - graphql-amqp-subscriptions-engine

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version: lts/*
          cache: yarn
      - name: Install dependencies
        run: yarn --immutable
      - name: Run packages/${{ matrix.package }} unit tests
        run: yarn run test:unit --coverage
        working-directory: packages/${{ matrix.package }}
      - if: ${{ !inputs.disable-coverage-archival && matrix.package == 'graphql' }}
        name: Archive coverage report
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
        with:
          name: unit-coverage-${{ matrix.package }}
          path: packages/${{ matrix.package }}/coverage/
