name: "Unit tests"

on:
  workflow_call:
    inputs:
      disable-coverage-archival:
        description: "Whether or not to archive the test coverage"
        required: false
        default: false
        type: boolean

jobs:
  unit-tests:
    strategy:
      matrix:
        package:
          - graphql
          - introspector

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
        with:
          node-version: 24
          cache: yarn
          package-manager-cache: false
      - name: Install dependencies
        run: yarn --immutable
      - name: Run packages/${{ matrix.package }} unit tests
        run: yarn run test:unit --coverage
        working-directory: packages/${{ matrix.package }}
      - if: ${{ !inputs.disable-coverage-archival && matrix.package == 'graphql' }}
        name: Archive coverage report
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: unit-coverage-${{ matrix.package }}
          path: packages/${{ matrix.package }}/coverage/
