name: "Apollo Federation Subgraph Compatibility"

on:
  workflow_call:

jobs:
  apollo-federation-subgraph-compatibility:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version: lts/*
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Install webpack-cli
        run: yarn add -D webpack-cli
      - name: Build compatibility test subgraph
        run: |
          yarn build
        working-directory: packages/apollo-federation-subgraph-compatibility
      - uses: apollographql/federation-subgraph-compatibility@b6981fd83d24450a7cbd2d7727196e0ba57614e0 # v2.1.1
        with:
          # [Required] Docker Compose file to start up the subgraph
          compose: "packages/apollo-federation-subgraph-compatibility/docker-compose-gha.yml"
          # [Required] Path to the GraphQL schema file
          schema: "packages/apollo-federation-subgraph-compatibility/schema.graphql"
          # Boolean flag to indicate whether any failing test should fail the script
          failOnWarning: true
          # Boolean flag to indicate whether any failing required functionality test should fail the script
          failOnRequired: true
      - name: Save PR number
        env:
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          mkdir prnumber
          echo "$PULL_REQUEST_NUMBER" > ./prnumber/prnumber
      - name: Archive PR number
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
        with:
          name: prnumber
          path: prnumber/
