name: "Integration tests (on-prem, Neo4j nightly build)"

on:
  workflow_call:
    inputs:
      disable-coverage-archival:
        description: "Whether or not to archive the test coverage"
        required: false
        default: false
        type: boolean
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
        description: "AWS Access Key ID"
      AWS_SECRET_ACCESS_KEY:
        required: true
        description: "AWS Secret Access Key"

jobs:
  ecr-login:
    runs-on: ubuntu-latest

    outputs:
      docker_user: ${{ steps.login-to-ecr.outputs.docker_username_535893049302_dkr_ecr_eu_west_1_amazonaws_com }}
      docker_password: ${{ steps.login-to-ecr.outputs.docker_password_535893049302_dkr_ecr_eu_west_1_amazonaws_com }}

    steps:
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@d539f0932e70871a027e9d5a9d8fc38589180a64 # v2
        id: login-to-ecr
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-1

  integration-tests:
    needs:
      - ecr-login

    strategy:
      matrix: # This matrix tests the minimum supported version of Node.js as well as the current lts
        node: [{ name: "20", coverage_name: "20" }, { name: "lts/*", coverage_name: "lts" }]
        packages:
          [
            { package: "introspector", shard: 1/1, coverage_name: 2 },
            { package: "graphql", shard: 1/4, coverage_name: 3 },
            { package: "graphql", shard: 2/4, coverage_name: 4 },
            { package: "graphql", shard: 3/4, coverage_name: 5 },
            { package: "graphql", shard: 4/4, coverage_name: 6 },
          ]
        graphql-version: [{ version: "^15.0.0", coverage_path: 15 }, { version: "^16.0.0", coverage_path: 16 }]
        neo4j-driver-version: ["^5.0.0", "^6.0.0"]

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - name: Setting up Node.js with version ${{ matrix.node.name }}
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: ${{ matrix.node.name }}
          cache: yarn
          package-manager-cache: false
      - name: Login to ECR
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4
        with:
          registry: 535893049302.dkr.ecr.eu-west-1.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Pull Neo4j dev image
        run: docker pull 535893049302.dkr.ecr.eu-west-1.amazonaws.com/build-service/neo4j:2025-enterprise-debian-nightly-bundle
      - name: Start Neo4j container
        run: |
          docker run \
          --name test-dev-neo4j \
          -d \
          --rm \
          -p 7687:7687 \
          --env NEO4J_AUTH=neo4j/password \
          --env NEO4J_PLUGINS=\[\"apoc\"\] \
          --env NEO4J_ACCEPT_LICENSE_AGREEMENT=yes \
          535893049302.dkr.ecr.eu-west-1.amazonaws.com/build-service/neo4j:2025-enterprise-debian-nightly-bundle
      - name: Install dependencies
        run: yarn --immutable
      - name: Overwrite GraphQL version
        run: yarn up --exact graphql@${{ matrix.graphql-version.version }}
      - name: Overwrite neo4-driver version
        run: yarn up --exact neo4j-driver@${{ matrix.neo4j-driver-version }}
      - name: Run @neo4j/graphql integration tests and move coverage
        run: |
          yarn test:int --shard=${{ matrix.packages.shard }} --coverage
          mv coverage coverage-nightly-${{ matrix.graphql-version.coverage_path }}
        working-directory: packages/${{ matrix.packages.package }}
        env:
          NEO_USER: neo4j
          NEO_PASSWORD: password
          NEO_URL: neo4j://localhost:7687
          USE_RESTRICTED_USER: true
      - if: ${{ !inputs.disable-coverage-archival && matrix.packages.package == 'graphql' }}
        name: Archive coverage report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: integration-nightly-coverage-neo-driver${{matrix.neo4j-driver-version}}-${{ matrix.packages.package }}-${{ matrix.graphql-version.coverage_path }}-${{ matrix.packages.coverage_name }}-${{ matrix.node.coverage_name }}
          path: packages/${{ matrix.packages.package }}/coverage-nightly-${{ matrix.graphql-version.coverage_path }}/
      - name: Stop Neo4j container
        if: always()
        run: |
          docker ps -a
          docker stop test-dev-neo4j

  merge-integration-tests-results:
    runs-on: ubuntu-latest
    needs: integration-tests
    steps:
      - if: ${{ !inputs.disable-coverage-archival }}
        name: Merge Artifacts
        uses: actions/upload-artifact/merge@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: integration-nightly-coverage
          pattern: integration-nightly-coverage-*
