name: "Unit tests"

on:
  workflow_call:
    inputs:
      disable-coverage-archival:
        description: "Whether or not to archive the test coverage"
        required: false
        default: false
        type: boolean

jobs:
  unit-tests:
    strategy:
      matrix:
        package:
          - graphql
          - introspector

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: 24
          cache: yarn
          package-manager-cache: false
      - name: Install dependencies
        run: yarn --immutable
      - name: Run packages/${{ matrix.package }} unit tests
        run: yarn run test:unit --coverage
        working-directory: packages/${{ matrix.package }}
      - if: ${{ !inputs.disable-coverage-archival && matrix.package == 'graphql' }}
        name: Archive coverage report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: unit-coverage-${{ matrix.package }}
          path: packages/${{ matrix.package }}/coverage/
