name: "Toolbox Deploy"

on:
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  deploy:
    if: github.event_name == 'workflow_dispatch' || startsWith(github.event.release.name, '@neo4j/graphql-toolbox')

    runs-on: ubuntu-latest

    environment: aws

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: yarn
      # the introspector is a referenced project by the Toolbox.
      - name: Build the introspector
        run: yarn build
        working-directory: packages/introspector
      - name: Build graphql-toolbox
        run: yarn build
        working-directory: packages/graphql-toolbox
        env:
          SEGMENT_GRAPHQL_TOOLBOX_DEV_SOURCE: ${{ secrets.SEGMENT_GRAPHQL_TOOLBOX_DEV_SOURCE }}
          SEGMENT_GRAPHQL_TOOLBOX_PROD_SOURCE: ${{ secrets.SEGMENT_GRAPHQL_TOOLBOX_PROD_SOURCE }}
          CANNY_GRAPHQL_TOOLBOX_APP_ID: ${{ secrets.CANNY_GRAPHQL_TOOLBOX_APP_ID }}
      - uses: jakejarvis/s3-sync-action@be0c4ab89158cac4278689ebedd8407dd5f35a83 # renovate: tag=v0.5.1
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-west-2"
          SOURCE_DIR: "packages/graphql-toolbox/dist" # optional: defaults to entire repository
